### ISSUE TITLE
forbidden use of missing_value in 2 examples

### ISSUE THREAD

**Issue by taylor13** [cf-convention/cf-conventions#162]
In appendix H.2.3 examples H.4 and H.5, `missing_value` is defined for the time coordinate, `time(time).`  CF forbids missing values in true dimension variables, so `time:missing_value = -999.9;` should be removed from each example.

**Comment by davidhassell** [comment]
I agree.

**Comment by ngalbraith** [comment]
Is there a rationale for forbidding missing values in dimension variables? Time is a perfect example, where there may be a bogus value in the record (occasionally, at least for instrument data) but the place holder is needed, since this is a dimension as well as a coordinate. Assuming that the rest of the record contains good data, we don't want to delete it all and may not want to replace the time value with the 'corrected' time (for various reasons, once again having to do with instrumentation, like monitoring the health of a clock or a logger).

This has been discussed over the years, but I can't recall why this rule exists.

**Comment by JonathanGregory** [comment]
Dear Nan

Missing data values aren't allowed in (dimension) coordinate variables because
the coordinate values must be monotonic (and numeric). Generic software can
assume they're all unique and it may do arithmetic with them as well. It's
allowed to have missing data in auxiliary coordinate variables, so you could
use one of those instead.

Best wishes

Jonathan

**Comment by JonathanGregory** [comment]
This issue proposes to delete incorrect missing_data attributes of time coordinate variables in two examples in Appendix H. It was raised by Karl @taylor13 more than 3 years (&Gt; 3 weeks) ago. @davidhassell and I agreed that he was right. It refers to an error in the document, so the issue should be treated as correcting a defect. No-one objected, and silence means tacit agreement. Therefore I have prepared a [pull request](https://github.com/cf-convention/cf-conventions/pull/379) to make the change. Please could someone check and merge it.

**Comment by davidhassell** [comment]
Thanks for following up on this, Jonathan, It will make it into CF-1.10.
