### ISSUE TITLE
Formatting errors in table of contents for examples.

### ISSUE THREAD

**Issue by martinjuckes** [cf-convention/cf-conventions#164]
**Title:** Formatting errors in table of contents for examples.
**Moderator:** @martinjuckes
**Requirement Summary:** (1) Numbering of index items is not consistent with target examples (e.g index entry `7.8. Climatological seasons` links to `Example 7.9. Climatological seasons`) , (2) examples 7.1 and 7.15 have no index entry, (3) Section 7.5 Geometries (including example 7.15) is included in the source document but omitted from the web page and pdf document.
**Technical Proposal Summary:** (1) Edit `toc-extra.adoc` to correct numbering of index items, (2) Correct an apparent error in defining the anchor for example 7.15 in `ch07.adoc`.

**Benefits:** Corrected index and inclusion of missing sub-section.
**Status Quo:** Index is incomplete and inacuurate.  
**Detailed Proposal:** 

- The numbering of the entries for examples 7.2 to 7.14 need to be corrected in `toc-extra.adoc` (currently set to 7.1 to 7.13);
- New entries need to be added to `toc-extra.adoc` for examples 7.1, 7.15 and 7.16 and for table 7.1;
- In `ch07.adoc` correct `[["timeseries-with-geometry"]]` to `[[timeseries-with-geometry]]`.
- The web page is more than a year behind the latest version in github .. missing Geometries section : is this intended?

To avoid potential conflict (unlikely) with formatting changes proposed in https://github.com/cf-convention/cf-conventions/pull/161, these changes are probably best tackled after that request is accepted.

**Comment by JonathanGregory** [comment]
Dear @martinjuckes 

Thanks for raising this issue, the best part of four years ago, that identifies a number of errors. I suspect no-one responded at the time because of the possible interaction, which you highlighted, with https://github.com/cf-convention/cf-conventions/pull/161. If you have a few minutes available, it would be helpful if you could say whether any of these errors still remain now. Perhaps they were corrected by another issue at some point.

Best wishes and thanks

Jonathan
