### ISSUE TITLE
Vertical coordinates when only the bounds of the cells are of interest

### ISSUE THREAD

**Issue by MaartenSneepKNMI** [cf-convention/cf-conventions#190]
In the current CF the following is needed to specify vertical profiles with boundary information:

```
dimensions:
    lon = 360;
    lat = 180;
    layer = 18;
    vertices = 2;

variables:
    float lat(lat);
        lat:long_name = "latitude";
        lat:units = "degrees_north";
        lat:bounds = "lat_bnds";
    float lon(lon);
        lon:long_name = "longitude";
        lon:units = "degrees_east";
        lon:bounds = "lon_bnds";
    float pressure(layer, lon, lat);
        pressure:long_name = "pressure grid";
        pressure:units = "hPa";
        pressure:bounds = "pressure_bnds";
    float lat_bnds(lon,vertices);
    float lon_bnds(lat,vertices);
    float pressure_bnds(layer,lon,lat,vertices);
    float O3(layer, lon, lat);
        O3:units = "1e-9";
        O3:coordinates = "pressure";
```

In this example one of the vertical interfaces is the tropopause pressure, which doesn't fit nicely into a compression scheme or parametrization. However, the only useful vertical grid are the interfaces, the pressures themselves are useless. Furthermore the pressure grid is complete, i.e. the boundaries fill the vertical completely from surface to the top pressure without gaps. An extra dimension would suffice to describe the vertical grid in a much more compact way:

```
dimensions:
    lon = 360;
    lat = 180;
    layer = 18;
    interfaces = 19;

variables:
    float lat(lat);
        lat:long_name = "latitude";
        lat:units = "degrees_north";
        lat:bounds = "lat_bnds";
    float lon(lon);
        lon:long_name = "longitude";
        lon:units = "degrees_east";
        lon:bounds = "lon_bnds";
    float pressure(interfases, lon, lat);
        pressure:long_name = "pressure interface grid";
        pressure:units = "hPa";
    float lat_bnds(lon,vertices);
    float lon_bnds(lat,vertices);
    float O3(layer, lon, lat);
        O3:units = "1e-9";
        O3:coordinates = "pressure";
```

In the current CF conventions the pressure information is almost 3 times larger than the data itself, which seems inefficient. The `n+1` method of storing the interfaces is rather common, for instance it is used by ECMWF in many of its datasets. 

I propose to allow an 'off by one' method of storing vertical information only as a pressure grid with only interfaces, rather than pressure levels.

**Comment by dblodgett-usgs** [comment]
OK. @czender or @MaartenSneepKNMI -- would you be willing to summarize the issue in the latest template? 
```
**Title:** Short and descriptive.  
**Moderator:** @user  
**Requirement Summary:** A few sentence functional summary  
**Technical Proposal Summary:** Brief proposal overview  
**Benefits:** Who or what will benefit from this proposal?  
**Status Quo:** Discussion of the current state CF and other standards.  
**Detailed Proposal:** Complete proposal
```

**Comment by JimBiardCics** [comment]
Here's a thought on how to address this. Create an attribute for a coordinate variable that declares whether the values are to be considered as applying to the cells or as applying to the cell boundaries. The default (if the attribute is not present) is that the values are to be considered as applying to the cells. This is akin to the image processing schemes in which cell location information references the center of a cell vs those where the location information reference a corner of a cell. (Always fun when people confuse the two!)

If a coordinate variable is declared to be an "interface" coordinate, you would be required to provide the far interface (the N+1 interface) in the coordinate variable. The data variable would reference the same dimension as the coordinate variable, just as we do now, but the values in the N+1 hyperslab would be set to **`_FillValue`** to denote that there is no data there. CDL for this would look something like:
```
dimensions:
    lon = 360;
    lat = 180;
    interfaces = 19;

variables:
    float pressure(interfaces, lon, lat);
        pressure:long_name = "pressure grid";
        pressure:units = "hPa";
        pressure:coord_type = "interface";
    float O3(interfaces, lon, lat);
        O3:units = "1e-9";
        O3:coordinates = "pressure";
```
The attribute **`coord_type`** (which is a strawman name) with a value of "interface" indicates how to interpret the values.

This could apply to any coordinate variable if we want to allow it.

**Comment by davidhassell** [comment]
I understand that difficulties that are trying to be addressed, here, but I am not in favour of this proposal. This is partly because I agree with the arguments laid out by @JonathanGregory  (https://github.com/cf-convention/cf-conventions/issues/190#issuecomment-77123170).

I'm also concerned about the dimension being sub-setted or reordered by a user. In general this would, I think, not be a well defined operation. For example, if the interfaces for 4 levels were `1 2 3 4 5`, what would the interfaces be if you created a new data variable from the first and third levels?  `1 ? 4`? This is not a problem with the existing conventions.

There is shortly going to be an issue that proposes an extension that allows coordinates and bounds (and any other geo-locating variables) to be external variables, so you could legally place your coordinates and/or bounds in a separate file. I appreciate that this may not be appropriate for particular use-case, but your comments on that would be most welcome.

Thanks,
David

**Comment by czender** [comment]
@JimBiardCics I like your idea because it directly addresses the main issue highlighted by Maarten and simplifies the overall storage scheme. Moreover, netCDF will automatically populate the last level of N+1 dimensional space with _FillValue if the nc_put_vara() routines are called with only N dimensions. I think storing coordinate info in a separate file is great for CMIP-style archives of thousands of single variable files  but is too heavyweight for most single-user applications.

**Comment by taylor13** [comment]
I want to make sure I understand the motivation.  Is the whole point to reduce the amount of storage  occupied by the coordinate information?  Or are there other practical or aesthetic considerations motivating the proposal?

**Comment by JimBiardCics** [comment]
@taylor13 I see the motivation as three-fold. There is the space issue, which I don't see as a major issue — particularly when compared with swath geolocation data. There is the repeated request by the user community for a scheme such as this. And then there is the conceptual difference between volume-oriented data and boundary-oriented data.

I'm more moved to make a change by the second two motivations, which I think are sometimes related. Certain disciplines prefer to associate data with the boundaries between cells as understood by CF rather than with points within the cells (such as the centers). CF can actually handle this on some level by specifying a boundary as the value in a coordinate variable and specifying the boundary and next boundary in a bounds variable, but if I have understood the discussions about this over the years, this approach is not intuitive for users in those disciplines. I think it may imply things that are incorrect in some cases.

As I said, I don't have direct experience with these sorts of difficulties, so if someone can do a better job of expressing the issues (assuming they do exist), please speak up.

**Comment by taylor13** [comment]
thanks, @JimBiardCics .  That's helpful.
I think the problem being addressed here could be better handled by extending the use of cell_methods to the vertical dimension.  As a reminder, in the horizontal we often have a grid defined at all cells over a domain, but for some cells the variable represents only a portion of the cell area.  For example, ``cell_methods = "area: mean over sea_ice"`` indicates that the value reported applies only the the portion of the cell covered by sea ice.  To subsequently compute an area-weighted mean of the quantity, one must access the grid cell areas and also the sea-ice area cell fraction.  

For the use case described above, I assume that the layers are constant pressure thickness except the layer adjacent the tropopause and the layer adjacent to the surface.  In this case I think the vertical coordinate could simply be pressure and the pressure bounds too could be constant across the globe .   We could extend the cell_methods to include something like:
``cell_methods="pressure: mean within troposphere"``  or ``where troposphere``
OR
``cell_methods="pressure: mean above surface, below tropopause`` 

where we would have a limited number of options on what could follow "within" (or "above" and "below"); for example, "atmosphere" (referring to the entire atmosphere above the surface), "troposphere", "stratosphere", etc. (or for the 2nd option "surface", "tropopause", "stratopause", etc.

In order to determine the pressure thickness of the cells adjacent to the earth's surface and adjacent to the topopause, the data provider would have to provide the surface pressure field and the tropopause pressure field (just as the case of horizontal grids, the data provider has to provide the area fraction for sea_ice in the analogous case.  

An advantage of this approach, is that only a single 3-d field is saved (supplemented by possibly two 2-d fields: surface pressure and tropopause pressure).

**Comment by czender** [comment]
@taylor13 I think your suggestion is most suited to the case where the pressure thicknesses of the internal layers are constant across a level, as you assume. I (and perhaps @MaartenSneepKNMI ?) am more concerned with the general case where the thicknesses vary horizontally and vertically. A CF-compliant way of storing the vertical bounds that requires only one 3D array (interfaces only), rather than three 3D arrays (centers, lower boundaries, and upper boundaries) would I think be closer to addressing the OP. The "interface" coordinate type suggested by @JimBiardCics seems to do that without too much complexity or too little generality. @davidhassell poses the issue of well-defined interface coordinates for vertically discontiguous hyperslabs, where up to 2*N interfaces (rather than N+1) are needed. It is a good question, though it does not exclude Jim's idea from consideration. A vertically discontiguous hyperslab with well-defined interfaces could be created by having two non-default coordinate types, "contiguous_interface" (with an N+1 dimension) and "discontiguous_interface" (with a 2*N dimension).

**Comment by JonathanGregory** [comment]
@MaartenSneepKNMI opened this issue in 2015. There was some discussion at that time, and some more (after a four-year pause) in 2019. Since then there have been no further contributions. The contributors have included @czender, @davidhassell, @taylor13 and myself. The discussion was about how to store the vertical coordinate of layer interfaces of 3D grid cells when the vertical coordinate depends on 2D location. The main motivation for the issue was a wish to conserve space in files.

Does anyone have a present use-case for this, or another reason for taking it forward? I propose to close this issue, marked as `dormant`, if no-one makes a new contribution to the issue before 8th January (four weeks from today i.e. allowing an extra week for the imminent holidays).

**Comment by davidhassell** [comment]
Thanks Jonathan. For the record, I'm fine with this issue being closed as "dormant" at this time.

**Comment by taylor13** [comment]
I have no interest in carrying this forward, so fine with it being closed (unless, of course, someone objects with reason).

**Comment by czender** [comment]
I agree with marking it "dormant".
