### ISSUE TITLE
Citation guidance and a DOI

### ISSUE THREAD

**Issue by martinjuckes** [cf-convention/cf-conventions#206]
**Title:**   Citation guidance and a DOI
**Moderator:** @user  
**Moderator Status Review [last updated: YY/MM/DD]:** Brief comment on current status, update periodically 
**Requirement Summary:** We currently lack clear metrics of usage of the CF Convention, though we know from many sources that it is widely used and required for many important activities. It is now very easy to obtain a DOI, and this is done routinely for many documents. 
**Technical Proposal Summary:** Place a PDF document for CF-1.7 and each 1.X update in Zendodo, and place citation guidance on cf-conventions.org. 
**Benefits:** The CF Convention will gain visibility through citation.
**Status Quo:** Lack of clear guidance on citation means that the work going into the convention is not properly acknowledged in the thousands of publications which rely on it. 
**Detailed Proposal:** 

(1) Place a pdf version of the convention in Zenodo (or equivalent) and obtain a DOI;

(2) Add the following to the web page:

> Please cite as:
NetCDF Climate and Forecast (CF) Metadata Conventions, Version 1.7. doi:10.5281/zenodo.xxxxxx, August 2017.

(3) Establish a procedure to repeat this with every 1.X version release.

**Comment by graybeal** [comment]
I totally support citation guidance. 

I am OK with creating the DOI (despite my love of IRIs :->). If we do that we should decide what the authoritative document is—the PDF that's cited, or the on-line document (which might go through minor updates).

Also, an option for you to consider: Creating the registered entity/DOI as the latest version, not a specific version. Then upload new revisions as needed to the single registered document/DOI. The citation is of the standard, not of a version of it. (I believe at least one of the document registries has built-in support for versions now, so that you can cite by versioned DOI but the registry also provides an aggregated DOI and statistics across all the citations. That would be ideal.)

**Comment by castelao** [comment]
Related issue #127

**Comment by bnlawrence** [comment]
There was a long discussion on ticket #127.   There was a consensus for just one uber DOI apparently in Reading, but I'd like to add a slight perturbation to that. As a funder, I would like to see a DOI for each major release, so that over time, different authors can get added and get credit for when they joined the fray. 

For avoidance of doubt, I would want scientists using CF in their analysis to use this citation in their papers' reference list, it is not intended as a replacement for the conventions string in files.

**Comment by martinjuckes** [comment]
Apologies to @rsignell-usgs  for duplicating the DOI issue he raised last year ... I'll close this one and raise a few point in #127 .
