### ISSUE TITLE
Should we clarify the backwards compatibility objective?

### ISSUE THREAD

**Issue by martinjuckes** [cf-convention/cf-conventions#207]
# Summary
## Title
Clarification of backwards compatibility objective
## Moderator
@erget 
## Moderator status review [last updated: 2019-12-30]
Explicit support from
- @martinjuckes 
- @JonathanGregory 
- @graybeal 

No objections expressed.

Consensus seems to be reached. Barring objections corresponding PR will be merged 2020-01-13.
## Requirement summary
CF strives to be backwards compatible, but when new attributes are controlled in CF there is the possibility of a clash with usage in previously CF-compliant data. Clarifying how CF achieves backwards compatibility would help users who need high stability.
## Technical proposal summary
As in #208.
## Benefits
Users would have a greater understanding of what is guaranteed, or not guaranteed, to be supported as the CF Conventions evolve.
## Status quo
- Current tools tend to not check the `Conventions` attribute, which is not required anyway
- We don't specify explicitly in what way backwards compatibility is maintained across versions
## Detailed proposal
Original post from @martinjuckes :
> This question is motivated by discussions at a recent WMO workshop discussing a pathway to increased future use of CF by the WMO. The issue of backward compatibility is important to the WMO: they accept that CF will evolve in ways which are dictated by the established rules and mechanisms, but want some assurances that anything the implement based on CF will not be undermined by future changes to CF. In principle this is can be guaranteed through our commitment to backwards compatibility, but there is a loophole in the form of a slight divergence between practise and the ideal we express. 
> 
> The slight loophole is reflected in the 8 attributes which had no meaning in CF-1.0 but have been assigned meaning in CF-1.7: `actual_range`, `cf_role`, `computed_standard_name`, `external_variables`, `feature_types`, `flag_masks`, `instance_dimension`, `sample_dimension`. The rate of addition of new attributes is agreeably slow, and the chances of a conflict with pre-existing usage are low. Nevertheless, it is clear that we do not have any mechanism or intention of checking that the attribute in question has not been used differently in pre-existing CF compliant netcdf files. That is, we believe that any usage of the 35 attributes defined in CF-1.0 which complies with CF-1.0 is compliant with CF-1.7, but usage of, for instance, `flag_masks` which complied (by default) with CF-1.0 may be non-compliant with CF-1.7.
> 
> In other words, the check on backwards compatibility mentioned in the [white paper on maintaining and advancing the standard](http://cfconventions.org/Data/cf-documents/cf-governance/cf2_whitepaper_final.html) only applies to previously defined attributes. 
> 
> First question: is the white paper the right place to look for a statement of our commitment to backwards compatibility? It is mentioned in section 2.3 of that document.
> 
> I don't think we should change our practise (I don't see any feasible alternative here), but, in order to avoid potential disappointment when dealing with organisations such as the WMO which are liable to take rigid interpretations of commitments we make, I feel there is a need of a caveat needed in the way we claim backwards compatibility. 
>

**Comment by JimBiardCics** [comment]
It seems to me that this is precisely the point of naming the version of CF used in the **`Conventions`** attribute. If you named CF 1.0 in a file, then nothing past CF 1.0 holds for that file. What is the scenario under which an actual problem arises?

**Comment by taylor13** [comment]
Here is an example:

Someone writes a CF 1.7 compatible file and includes an attribute (not currently described by the CF convention) named ``frequency``, which identifies the sampling frequency for data included in the file according to a controlled vocabulary (e.g., "hourly", "daily", "monthly").  The dataset is written without defining the ``Conventions`` attribute.

Now suppose at some point in the future the CF community (which may be unaware of the file described above) decides it would like to enhance the CF conventions by including an attribute named ``frequency`` with a controlled vocabulary that includes "hour", "day", "month", "year".  The CF checker would have to be able to check whether the assigned value for ``frequency`` was consistent with the controlled vocabulary.  Suppose this were release CF 1.22

If this updated CF checker were run on the file described in the first paragraph above, which was produced before the enhancement to CF, the checker would find the file to be non-compliant, when it should find it compliant under CF 1.7, but non-compliant under CF1.22.  

We could perform a proper check on the sample file if the ``Conventions`` attribute were *required*.  Then the checker could perform different checks depending on the which release was specified there.  (Note that currently the ``Conventions`` attribute is only "recommended", not "required"). 

Requiring the ``Conventions`` attribute doesn't prevent all confusion, however.  Users would have to be aware that something like ``frequency`` has a standardized interpretation, as far as CF is concerned, only if the ``Conventions`` attribute specifies a version of 1.22 or later.  A ``frequency`` attribute written before 1.22 might be interpreted in an entirely different way (unconstrained by CF).

**Comment by DocOtak** [comment]
I'm in agreement with @JimBiardCics regarding the purpose of the "version". At the CF meetings at summer ESIP, there was a suggestion to switch to using semantic versioning, but that has not been adopted.

The following are just my how I was thinking regarding this:
When thinking about this issue... I eventually decided that CF is not backwards or forwards compatible with itself, but might be backwards compatible with COARDS, though I don't know enough about COARDS to really conclude this.

For the purposes of the WMO, I don't think "backwards compatible" is a promise that can be made to them. The CF conventions are a community and essentially "living standard" which is always (slowly) changing in response to user request and needs. I think if the WMO wants to adopt a "strict" version of this, they would need to publish that themselves or at least specify an exact CF version.

To make this promise I would imagine the following would need to happen:
* Frozen data model (#159), I've heard many people say at meetings that CF is not explicitly tied to netCDF as a data format, however, almost all of the CF documentation talks about netcdf as the data format it uses.
* Since features outside of "netcdf classic" have already been added (e.g. strings, groups), then #191 would need to be resolved. Since most of the features are available in netCDF4 anyway, I imagine it is a "how" and "when" these are added to CF, not an "if".
* Either a commitment to *never* add new standardized attributes to CF, or disallow the use of non standardized attributes in files claiming to be CF.

Since the "standard_name" list isn't tied to a specific version of CF, they do have some tacit agreement to never remove or change the definition of an existing name in a non backwards compatible way.

**Comment by martinjuckes** [comment]
Thanks for those comments. The case outlined by Karl illustrates the point I was concerned with.

In response to Andrew (@DocOtak), I'd just like to clarify that I'm trying to clarify the existing policy on backwards compatibility in order to avoid confusion in our conversation with WMO, I don't see any need to change it for them change it for them.

Jonathan (@JonathanGregory ) often refers to backward compatibility, but it appears there are different views on the subject. My understanding was that:

> (a) Future modifications of CF are intended to preserve backward compatibility so that files which comply with the current version will continue to comply with future versions;

> (b) The intention is that software which is designed to work with the current version of CF should automatically function with earlier versions.

It is clear that Andrew and Jim disagree with (a), but I'm pretty sure it was a view expressed by members of the CF Governance Panel to the WMO representatives at the meeting last week. Did I misunderstand this (@JonathanGregory )?

**Comment by JonathanGregory** [comment]
Dear @martinjuckes and all

I agree that CF is already backwards-incompatible in the way illustrated by Karl's example. That is similar to what we discussed as "extensions" with the WMO; an extension e.g. a new attribute may conform to the present CF but become incompatible with a future version of CF.

I believe that, so far, CF versions are backwards-compatible in the narrower sense that any metadata which is defined according to explicitly stated conventions in any previous version also conforms with the present version. (This is what @martinjuckes says in his third paragraph.) I accept that what @JimBiardCics says ("If you named CF 1.0 in a file, then nothing past CF 1.0 holds for that file") is logical and workable, but I think that nonetheless we should continue to maintain backwards-compatibility (in the sense of this paragraph) whenever we can. This is because it's likely that there are many present and future users of CF who will read or write files using software which is not sensitive to the `Conventions` attribute. Of course, one can tell them they have no-one to blame but themselves if they use careless software, but it's more helpful to them, and to the value of CF, if we avoid causing hazards and problems when we can.

I don't advocate this kind of backwards-compatibility as a principle of CF design as strongly as some of our other ones (like not doing things without use cases) but I think it's worth adhering to if it doesn't impede progress. I agree it would be helpful to define what we mean by backwards-compatibility when stating this intention.

Cheers

Jonathan

**Comment by JimBiardCics** [comment]
I think @JonathanGregory has put it well. In slightly different words, I see backwards compatibility as:

A later version of CF will not make invalid a compliant usage of an earlier version of CF terms and forms.

Any stronger guarantee would put CF in such a straightjacket that we would be unable to develop it further.

**Comment by erget** [comment]
For what it's worth I agree with @JimBiardCics 's sentiment - data encoded in CF-1.2 should be readable for a client aware of CF-1.5, but a CF-1.5 compliant file may not be readable for a client that only is capable of reading CF-1.2. And in any case any client should warn about the Conventions attribute if it finds one that it doesn't know how to interpret.

More backwards incompatibility isn't really necessary in my view; one can use the Conventions attribute to verify that one can read the data and that is in my view sufficient.

**Comment by taylor13** [comment]
Whatever the meaning of "backward compatibility", I think we need to decide 
1. how the CF checker should treat attributes that are added to a later version of the conventions, and
2. whether we want to make the ``Conventions`` attribute mandatory.

I recommend that
1. The ``Conventions`` attribute should become mandatory and include the CF version (in the form "CF-y.x", where y and x are integers).
2. The CF checker could assume any file *without* a ``Conventions`` attribute might only be compliant with versions of the conventions promulgated prior to the one when ``Conventions`` became mandatory.
3.  As new attributes become added to CF (which might have names conflicting with attribute names in existing CF-conforming files, but now defined differently by CF), these new attributes would be checked by the CF checker *only* if the ``Conventions`` attribute indicates the file conforms to a CF version where these attributes are described.  If the ``Conventions`` attribute is undefined or indicates a CF version earlier than when the attribute was added to the conventions, the CF checker would not check the attribute for conformance and not raise an error.  (In this case conformance would be assured only with CF versions appearing before the introduction of the new attribute.)

**Comment by martinjuckes** [comment]
Hello Karl, Daniel,

I agree with recommendations 1. and 2. [above](https://github.com/cf-convention/cf-conventions/issues/207#issuecomment-535634848), but, in 3. I think what we need is already covered by the CF checker.

Currently (v3.1.1 on my laptop), the checker uses the latest conventions version by default. A warning is issued if the `Conventions` attribute is either absent of different from the current. You can use the command line to specify that checks are against either the version specified in the file or a specific version entered on the command line (presumably this would be useful if your software is expecting a specific version). That is, the user has some flexibility to determine what version of the Convention is checked against. [@RosalynHatcher : is this an accurate description of how the checker deals with the Conventions attribute?].

There would be a need to update some of the warning message. E.g. if there is no `Conventions` attribute in the file, this warning is given:
> WARN: (2.6.1): No 'Conventions' attribute present

Under the proposed changes, an absent `Conventions` attribute would be either an error under the latest convention or a unspecified version in a file which complies with an earlier version. For checks carried out under the new rules, something along the lines of the following might work:

> ERROR: (2.x.y): 'Conventions' attribute absent. This attribute is required in versions 1.8 and later. The file may comply with earlier versions of the CF Convention. Use the '-v' flag if you want to check compliance with a different version.

**Comment by ngalbraith** [comment]
> ...data encoded in CF-1.2 should be readable for a client aware of CF-1.5, but a CF-1.5 compliant file may not be readable for a client that only is capable of reading CF-1.2. 

I think a CF-1.5 compliant file should certainly be readable by a client written for CF-1.2; some new aspects of the standard will simply not be understood implicitly, but they won't break anything.

**Comment by taylor13** [comment]
Are there any objections to proposing that the ``Conventions`` attribute become required?  I think the CF checker would be affected but probably not other software.

**Comment by JimBiardCics** [comment]
@taylor13 I think that sounds entirely reasonable.

**Comment by martinjuckes** [comment]
I think this is a very good idea. It looks as though only changes in [sections 1.3](http://cfconventions.org/cf-conventions/cf-conventions.html#_overview) (2nd paragraph) and [2.6.1](http://cfconventions.org/cf-conventions/cf-conventions.html#identification-of-conventions) (1st paragraph) would be needed.

In the 1st paragraph of 2.6.1 there is also an obsolete reference to an FTP server where there used to be a collection of conventions documents: UNIDATA now just maintains a website pointing to online resources for each convention. This could be cleaned up at the same time.

Karl (@taylor13): do you think it would be appropriate to include (in section 2.6.1) some clarification of the relationship between conventions versions? E.g., along the line of Jim's phrase above: [A later version of CF will not make invalid a compliant usage of an earlier version of CF terms and forms](https://github.com/cf-convention/cf-conventions/issues/207#issuecomment-535021478).

**Comment by erget** [comment]
Hi all,
I've taken the liberty of putting together a pull request that implements these changes. My survey of the text leads me to believe that this does not introduce any inconsistencies. You can see the text in PR #208. How do you find it?
Daniel

**Comment by taylor13** [comment]
thanks, @erget .  Is the following statement really what we want to say? 
```
However, later versions of the CF Conventions will not make invalid a compliant usage of 
earlier versions of the CF terms and forms.
```
Files written prior to version 1.8, for example would be non-compliant with 1.8 if they didn't include the ``Conventions`` attribute, although they would remain compliant with earlier versions of the conventions.  Is that consistent with the above statement?

**Comment by erget** [comment]
My interpretation is that a file without the Conventions attribute set to 1.8 would only be compliant with earlier versions anyway, as this would make the Conventions attribute mandatory from 1.8. However, they would still be compliant with the version that was used to write them.

The intent of the text is to state that a client "aware" e.g. of CF-1.20 should be able to read a file written using CF-1.8, because the meaning of attributes used in CF-1.8, e.g. standard_name, would not be replaced by a new attribute with a different meaning. If we did decide to abandon standard_name (which I am definitely not advocating! This is simply a thought experiment) we could only do so by discontinuing its use and instead using an attribute with a different name.

**Comment by martinjuckes** [comment]
Hi Daniel,

Thanks for taking the initiative.

(1) The requirement should be that the `Conventions` attribute contains the string `CF-1.8` -- it can also contain references to additional conventions.

(2) As we are specifying `CF-1.8`, I think we should provide either a persistent link to that version (e.g. a DOI if that is agreed in #127 ) or just a link to the [cfconventions.org](http://cfconventions.org). Linking to the "latest" page will be misleading when 1.8 is no-longer the latest.

(3) Putting the discussion about relationships between different CF versions after the paragraph about including references to other conventions looks confusing to me. I would add the sentence from Jim there, adjusted to fit the paragraph. E.g. 
> This version of the CF Convention (and any subsequent versions) can be found on cfconventions.org. Subsequent versions of the CF Conventions will not make invalid a compliant usage of this and earlier versions of the CF terms and forms.

(4) I don't see the need to refer to putting multiple CF version numbers in the Conventions attribute .. if we refer to this practice, I think we should ban it. Is there a use-case?

(5) I would also leave out the text saying software developed for this version won't necessarily understand new features -- surely that is self-evident?

**Comment by erget** [comment]
@martinjuckes point by point:
(1) - right you are, I've changd it.
(2) - agreed. I'm a bit confused about the webpage because I thought it was possible to also find older versions of the CF Conventions there, but I only find the latest one and the current working draft. We should at least link back to the GitHub repository if we want to keep it this way. This is a different issue and probably belongs to the larger discussion @ethanrd was interested in starting concerning reworking the webpage. For now I've linked straight back to http://cfconventions.org/
(3) - I get what you're saying here, I've adopted roughly that wording and moved it directly behind the sentence linking back to the webpage.
(4) - I definitely don't see one, I'd been extrapolating a desire to have some clarity here from the discussion in this thread. I'm happy to remove it and have done so.
(5) - see (4).

**Comment by martinjuckes** [comment]
@erget : thanks. On point (2), there is a full list of past versions here: [http://cfconventions.org/documents.html](cfconventions.org/documents.html) -- so you could use that instead.

**Comment by erget** [comment]
Yes, but I don't see a link to it from the other pages so it's kind of an orphan (unless I'm just not finding it - I'm at a workshop right now so I've had limited time to dig for the URL). Therefore I'd prefer to leave the URL pointing to the main page, especially in light of the fact that the website may be restructured anyway.

Note to self that if this text is accepted, am update to the Conformance document will be required.

**Comment by martinjuckes** [comment]
OK. The link from the main page is in the "Documents" tab at the top ... it could be clearer. There may be a case for rationalising the relationship between [latest.html](http://cfconventions.org/latest.html) and [documents.html](http://cfconventions.org/documents.html), and how they are linked to -- but that would be for a new issue after this is completed.

**Comment by erget** [comment]
Agreed. Now I see why I wasn't able to find the link - when viewing the website on a small device, such as my phone in this case, the tab bar at the top Isn't shown! It's obvious from a desktop but not from tiny screens. I agree though that this is a separate issue from this one.

**Comment by JonathanGregory** [comment]
Dear Daniel, Martin et al.

Thanks for this proposal. I support the proposed text changes. I have a small suggestion, that in both places it could say "Files that follow this version of the CF Conventions" i.e. inserting _this version_. Other versions would not have to say "CF-1.8". It may be self-evident but it's useful to be explicit, especially to avoid implying that all existing files written for previous versions without the `Conventions` attribute have become invalid.

I think the definition stated of backwards-incompatibility is what we can practically adhere to. Nan suggested it could work the other way e.g. "a CF-1.5 compliant file should certainly be readable by a client written for CF-1.2". I agree that this holds for attributes that didn't exist in CF-1.2, which should be ignored silently, since that is not an error. However there are many kinds of change we could need to make that would break this kind of compatibility. For example (1) we generalised the `grid_mapping` attribute from its original form to its present form, which would probably not be compatible with the expectations of earlier software, (2) if 2D lat and lon auxiliary coordinate variable become optional provided that a `grid_mapping` is provided, that would present problems for earlier software. I think it would be too restrictive to adhere to this kind of backwards-compatibility, which is not proposed in the current text.

Best wishes, Jonathan

**Comment by erget** [comment]
@JonathanGregory agreed, I've updated the text.

**Comment by graybeal** [comment]
Strongly support the changes as most recently discussed, including Jonathan's point. Requiring the version is a huge improvement.

Regarding the full list of past versions at http://cfconventions.org/documents.html, even if there is no link to it that's a web site deficiency. I think it's important to link directly to the actual list of versions, that is a central resource for CF that should never go away. 

Sorry if you may have made this comment moot already

**Comment by dblodgett-usgs** [comment]
I've not had time to take this issue in, but I notice that it does not have a moderator assigned. Can someone who's taken part summarize the discussion and suggest whether it is concluded or not? I'll gladly assign a moderator who wants to be identified as such!

**Comment by erget** [comment]
I've added a summary. It's also worth noting that an update to the CF Checker is underway that would ameliorate some of the issues noted above. I noticed that some changes to the Conformance document had already been made but I've updated these to what I consider a clearer formulation.

**With no further objections I propose to merge the corresponding pull request in 2 weeks, on 2020-01-13. Please shout if you don't agree with this plan.**

On a separate note I agree with [@DocOtak's comment](https://github.com/cf-convention/cf-conventions/issues/207#issuecomment-534785288), points (1) and (2), and hope that we resolve those soon.

**Comment by erget** [comment]
PS: I've also updated the original post to include the full quote of @martinjuckes's proposal plus my summary. His text is unchanged and quoted; everything else is from me.

**Comment by dblodgett-usgs** [comment]
Fantastic. A model to follow I think. 

In case others have not seen it, any edited comment has a drop down to access the history of that comment as well. The summary comment of this issue says it was lasted edited by @erget and has the option to see those changes.

**Comment by graybeal** [comment]
I'm confused about one line, sorry if this is a basic misunderstanding:

> Subsequent versions of the CF Conventions will not make invalid a compliant usage of this or earlier versions of the CF terms and forms.

I understand we want/expect any CF tool to be able to read CF files from previous CF versions, so it makes sense that we don't want to invalidate those earlier files.

But if I use an attribute name in my CF 1.8 compliant file, and then later (say CF 1.9) the CF standard (unknowingly of course) uses that same attribute for a specific purpose (incompatible with the purpose I used it for in my 1.8-compliant file), how will that not make my compliant usage invalid? How is this accidental re-purposing avoidable?

I just can't figure out how any tools would implement that, without having a whole bunch of historical libraries for reading files from older versions of CF.

**Comment by erget** [comment]
@graybeal this gets to the heart of the discussion thus far in this thread. You're right, if somebody uses an attribute we don't know about, there's no way to guarantee that we won't reserve that attribute for something else in the future.

My understanding of that sentence is that we won't invalidate previous practices from the CF Conventions - anything that users do outside of the CF Conventions, like using their own attributes, is fine, but of course as you say we can't know if we break that. What we are saying is that we don't want to break uses of attributes that **are** governed by CF by changing their use in future versions.

**Comment by JimBiardCics** [comment]
@graybeal I read and understand the sentence in question this way:

A file that is compliant with a particular version of CF and contains a declaration of the CF version used is not made invalid by any later change to CF that would make the same file non-compliant if it was declared to use that later version. The fact that a change made in CF 1.9 invalidates a standard or non-standard practice in a file built using CF 1.8 doesn't make the CF 1.8 - compliant file invalid, as long as I have a **`Conventions`** attribute in the file that declares CF-1.8.

**Comment by erget** [comment]
Dear all,

Thanks for the productive conversation around this topic - consensus seems to have been reached and therefore as noted previously I am merging this request.
