### ISSUE TITLE
Inconsistent usage of false_easting and false_northing in grid mappings definitions and in examples

### ISSUE THREAD

**Issue by neumannd** [cf-convention/cf-conventions#212]
# Summary
## Title
Inconsistent usage of `false_easting` and `false_northing` in grid mappings definitions and in examples
## Moderator
@erget 
## Moderator status review
Explicit support from
- @JimBiardCics 
- @marqh 
- @JonathanGregory 
- @erget 

No objections expressed in this discussion.

https://github.com/SciTools/iris/issues/3626 notes that the current inconsistency sometimes leads to problems; @erget has proposed that solving the ambiguity would at least make the intent of the Conventions clear. Impact: Software would need to be aware of the defaults.

## Requirement Summary
Definitions of grid mappings / projections and their usage in examples should be consistent with respect to required attributes. 

## Technical Proposal Summary
As in #225.

Add `false_easting` and `false_northing` to [example 5.7](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#lambert-conformal-projection) or make them optional in the definition of all projections where applicable (e.g. [Lambert Conformal Conic projection](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#_lambert_conformal)).

## Benefits
Consistency 
## Status Quo
The attributes `false_easting` and `false_northing` are required in the grid mapping variable for a [Lambert Conformal Conic projection](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#_lambert_conformal). [Example 5.7](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#lambert-conformal-projection) does not use `false_easting` and `false_northing`.
## Detailed Proposal
Either `false_easting` and `false_northing` should be made optional in the definition of the projections (assumed to be zero if not set) or they should be added to example 5.7. I would prefer the first option as it is already the case for the attribute `north_pole_grid_longitude` in the grid mapping for [rotated poles](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#_rotated_pole):

> `north_pole_grid_longitude` - This parameter is option (default is 0).

Hence, I would suggest to replace 

> `false_easting`
> `false_northing`

in **all** grid mapping definitions by

> `false_easting` - This parameter is option (default is 0).
> `false_northing` - This parameter is option (default is 0).

**Comment by neumannd** [comment]
Shouldn't it be *This parameter is option**al** (default is 0).* instead of *This parameter is option (default is 0).*? If yes, should I create another issue for it or can it be done via this one?

**Comment by erget** [comment]
@dblodgett-usgs I'd be willing to moderate this one but can't self-assign. Could you check my privileges?

**Comment by erget** [comment]
@neumannd I'm happy to moderate this and await responses from the community. IMHO the editorial correction you suggest in the second comment can be addressed in the same issue.

**Comment by JimBiardCics** [comment]
I agree that  false_easting and false_northing should be made optional with assumed default values of zero.

**Comment by marqh** [comment]
hello @neumannd 

I think this is sensible as well.

Given the broad support, it would be good to see a Pull Request created, with the explicit changes proposed, to enable a more detailed review and a following commit to master.

As you content to create this Pull Request and propose changes to the document yourself?

thank you
mark

**Comment by neumannd** [comment]
@marqh I will create a pull request the next days and submit it.

**Comment by JonathanGregory** [comment]
Thank you, all. I support this as well.

**Comment by erget** [comment]
PR #225 looks OK to me. I've requested a formatting change that won't affect content in any way.

Current status looks like consensus to me and >2 committee members have expressed support. I'm starting the 3 weeks timer, after which I will merge provided that a sample file has been provided (@neumannd can you please do this?) and no objections are raised.

**Comment by neumannd** [comment]
> I'm starting the 3 weeks timer, after which I will merge provided that a sample file has been provided (@neumannd can you please do this?) and [...].

@erget: Do you mean a sample netCDF file that is uses this new feature (some projection information with `false_easting = 0` and `false_northing = 0`)?

**Comment by erget** [comment]
@neumannd yes - whereas I think it would be best if the sample data sets these values to 0 by omitting them. This is to make sure that the merge is in line with the [rules for changing the Conventions](http://cfconventions.org/rules.html):

> Once the summary has been made, if the test netCDF file does not yet exist, it must be created (unless the summary suggests the proposal should be rejected).

**Comment by davidhassell** [comment]
I've just been reviewing all of the issues in advance of 1.8, and whilst I said "already merged" issues will be included (https://github.com/cf-convention/discuss/issues/26), I should have said "merged by 31st January 2020". It looks like this should have passed the 3 week timer by then. The sample file isn't mandatory, and this seems like a straight forward change. Therefore I think that whilst a sample would be great, I personally would be happy merge in 8 days time (this side of February!) regardless. What do you think, @erget, @neumannd?

**Comment by neumannd** [comment]
Excuse me that I did not provide a file. I will add a file until end of this week.

**Comment by erget** [comment]
Fine by me, I'll merge this as soon as the sample file is uploaded or on 2020-01-27 at latest.

**Comment by neumannd** [comment]
@erget : Sorry for the delay. I forget to upload the files in the end of last week.

Attached a netCDF (als zip archive) and a CDL file (with `txt` ending).

[example_file_cf_issue_212.zip](https://github.com/cf-convention/cf-conventions/files/4128680/example_file_cf_issue_212.zip)
[example_file_cf_issue_212.txt](https://github.com/cf-convention/cf-conventions/files/4128683/example_file_cf_issue_212.txt)

**Comment by erget** [comment]
Many thanks, they're still good to have!

**Comment by davidhassell** [comment]
@erget Was there a PR associated with this? Thanks

**Comment by davidhassell** [comment]
... Sorry, I see it now (#225)

**Comment by cf-metadata-list** [comment]
Guten Morgen Daniel,

dank Deiner reminder scheinen ja die meisten unserer Vorschläge noch in 
die neue Version reinzukommen.
Aber hast Du eine Idee zu
https://github.com/cf-convention/discuss/issues/23
??
Ich glaube, man braucht immer noch etwas Neues für die cell_methods, um 
die Ursprungsauflösung in der Zeit mitliefern zu können.
cell_methods = "time: distribution (interval: 40 s)"

vielleicht??

Liebe Grüße
Beate


Von:    "Daniel Neumann" <notifications@github.com>
An:     CF-METADATA@LISTSERV.LLNL.GOV
Datum:  29.01.2020 16:01
Betreff:        Re: [CF-metadata] [cf-convention/cf-conventions] 
Inconsistent usage of false_easting and false_northing in grid mappings 
definitions and in examples (#212)
Gesendet von:   "Parent list for all CF discussions" 
<CF-METADATA@LISTSERV.LLNL.GOV>



@erget : Sorry for the delay. I forget to upload the files in the end of 
last week.
Attached a netCDF (als zip archive) and a CDL file (with txt ending).
example_file_cf_issue_212.zip
example_file_cf_issue_212.txt
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
This list forwards relevant notifications from Github. It is distinct from 
cf-metadata@cgd.ucar.edu, although if you do nothing, a subscription to 
the UCAR list will result in a subscription to this list. To unsubscribe 
from this list only, send a message to 
cf-metadata-unsubscribe-request@listserv.llnl.gov.


Helmholtz-Zentrum Geesthacht 
Zentrum für Material- und Küstenforschung GmbH 
Max-Planck-Straße 1 I 21502 Geesthacht I Deutschland/Germany 

Geschäftsführung/Board of Management: Prof. Dr. Matthias Rehahn, Silke Simon 
Vorsitzender des Aufsichtsrates/Chairman of the Supervisory Board: Ministerialdirigent Dr. Herbert Zeisel 
Amtsgericht Lübeck HRB 285 GE (Register Court) 
Internet: http://www.hzg.de
