### ISSUE TITLE
featureType in the absence of "discrete point location"

### ISSUE THREAD

**Issue by TomLav** [cf-convention/cf-conventions#220]
Dear all,

My question is about the notes below Table 9.1 (http://cfconventions.org/cf-conventions/cf-conventions.html#_features_and_feature_types) describing the featureTypes.

In particular: "time series that refer to a geographical region (e.g. the northern hemisphere)".

The document currently states: "Future versions of CF will generalize the concepts of geolocation to encompass these cases." and I am asking if the discussion leading to the generalization of the concepts of geolocation has started, and where to follow it.

My use case: I produce climate indicators that typically are time series of a numerical value that was computed by summing/averaging over large extents (e.g. sea-ice extent for the Northern Hemisphere) and I am wondering if these can be coded with featureType="timeSeries"

**Comment by dblodgett-usgs** [comment]
Hi @TomLav -- thanks for reaching out.

That discussion was partly taken up in the development of: http://cfconventions.org/cf-conventions/cf-conventions.html#geometries but as you can see in Example 7.15, the point coordinates are still more or less required to use the timeSeries feature type. 

From my perspective you have two options: 1) use (a) fake or (b) highly idealized point coordinates so client code will read the `timeSeries` data with maybe unfortunate handling of spatial data, or 2) leave out the spatial coordinates and use the rest of the `timeSeries` feature type and suggest some edits to the spec that allow that encoding to be valid. 

In 2, I would want to see a mechanism to reference some external description of the region -- possibly including a polygon geometry. Which could then circle back to putting a geometry (maybe just a convex hull) in the NetCDF file and using the centroid of the polygon as an idealized point location. This ends up looking an awful lot like 1b described above. and would put the onus on you to create .bounding polygons and idealized point locations.

Hopefully that's helpful. 

- Dave

**Comment by JonathanGregory** [comment]
Dear Thomas @TomLav

In answer to the question, No, I don't think it's been discussed already. Cases like this can be described without DSGs and featureTypes by providing a scalar or auxiliary coordinate variable with a string value and `standard_name` of `region` to identify the region, as described in 6.1.1. The reason this is problematic for chapter 9 is that it lacks x and y coordinate variables. It seems to me that it would be fine to provide a string-valued region variable instead of x and y variables if you want to store the data as a DSG, and you don't want to sketch out the regions explicitly (as in geometries). I don't have a view on whether this should still be regarded as a `featureType="timeseries"` or some new type.

Cheers

Jonathan

**Comment by TomLav** [comment]
Hei Jonathan and Dave,

Thank you for the replies and suggestions.

I do not necessarily need this to be DSG, but am experiencing issues from a third-party software that will allow time-series plotting only if it finds "featureType='timeseries'" in the file. The more I think of it, the more this seems to be an non-optimal assumption by the third-party software.

So I will now move away from DSG and adopt the "region" coordinate variable as suggested by Jonathan.

Hopefully, in the future, DSGs will adopt geometries (sect 7.5) and/or region strings (chapter 6) as location coordinates, but this has probably larger impacts than I can imagine.

Thomas
