### ISSUE TITLE
Incorporate the Conformance document into this repository

### ISSUE THREAD

**Issue by davidhassell** [cf-convention/cf-conventions#221]
**Overview**

I would to suggest, as a result of having spoken to various people about this, that we move the conformance document (https://github.com/cf-convention/Conformance/blob/master/conformance.adoc) to this repository.

**Why?**

Many enhancements to the CF conventions require changes to the conformance document. At present, theses must be submitted as a separate pull request to the https://github.com/cf-convention/Conformance repository. As a result, changes to the the conformance document are currently more likely to get overlooked and entail more work.

If the conformance document lives in this repository then one pull request can contain the enhancement and its conformances, reducing work and improving provenenance.

**Detailed proposal**

There would be no change to conformance document's status as an independent entity (http://cfconventions.org/Conformance/conformance.html). The only change would be that the `conformance.adoc` file will live in this repository instead of its current location. No existing files in this repository need to be changed.

The change would happen at the time of the release of CF-1.8. The existing https://github.com/cf-convention/Conformance repository will remain as an archive of changes to the conformance document for all versions up to and including CF1.8. All conformance changes for enhancements that make it into CF-1.9 will be recorded in the new https://github.com/cf-convention/cf-conventions/conformance.adoc file.

Please let me know what you think about this suggestion.

Many thanks,
David

**Comment by JonathanGregory** [comment]
I think this proposal is logical and will be helpful. I support it. Thanks.
Jonathan

**Comment by martinjuckes** [comment]
Good idea. I support it as well. Is it worth doing a minor reorganisation of this repository at the same time, and creating separate folders for the Conventions and Conformance documents?

**Comment by davidhassell** [comment]
@martinjuckes I would support the use of Conventions and Conformance sub-folders.

**Comment by erget** [comment]
I support this idea as well. I also believe that we can import the commits so that we have the full history in this repository, rather than the other one - happy to support with this one. @davidhassell would you like to implement this or are you looking for a volunteer / partner in crime?

**Comment by davidhassell** [comment]
@erget incorporating the commit history would be excellent, and presumably means that we could deprecate (in some way) the old repository. I would be delighted if you wanted to help with what sounds to me like advanced-level GitHub magic.

I see that the Conformance repo has a https://github.com/cf-convention/Conformance/blob/master/.travis.yml file for building the conformance document. This would have to transferred to the new repo, too.

**Comment by erget** [comment]
I'm not an expert on Travis but I'll try to import the document next week, in its own folder.

**Comment by DocOtak** [comment]
A question, would built changes done to the conformance doc be put in the gh-pages branch of the currently existing [Conformance](https://github.com/cf-convention/Conformance) repository so the draft would continue to be served from the same URI?

I've always wondered why these are actually separate documents, why isn't the conformance requirements included as an appendix or full on section of the cf-conventions?

#### Long Explanation of gh-pages question
There is currently a bit of github magic happening with regards to how this document is being served. Here is a summary:
* http://cfconventions.org/ is being served by github pages as the organization page from the [cf-convention.github.io](https://github.com/cf-convention/cf-convention.github.io) repository
* The [draft cf-conventions](http://cfconventions.org/cf-conventions/cf-conventions.html) document is being served as a project page from the [gh-pages branch of the cf-conventions repository](https://github.com/cf-convention/cf-conventions/tree/gh-pages) 
* The [draft conformance](http://cfconventions.org/Conformance/conformance.html) document is being served as a project page from the [gh-pages branch of the Conformance repository](https://github.com/cf-convention/Conformance/tree/gh-pages)

Because of the github [project pages rules](https://help.github.com/en/github/working-with-github-pages/about-github-pages#types-of-github-pages-sites), if the conformance document was merged into this repo, and also served from this repo's gh-pages branch, then the draft URL would change from http://cfconventions.org/Conformance/ to http://cfconventions.org/cf-conventions/Conformance/ assuming it exists as a "Conformance" directory.

**Comment by cf-metadata-list** [comment]
I configured the travis setup on the repository so I can likely offer some input if you hit issues

mark

________________________________________

**Comment by ethanrd** [comment]
@marqh - I'm guessing that last comment was you but it came in as @cf-metadata-list for some reason.

**Comment by marqh** [comment]
> I configured the travis setup on the repository so I can likely offer some input if you hit issues mark

@ethanrd yes, this was me; I attempted to shortcut the comms process, and hit reply on an email notification. who knew that this would anonymise the response and tag it as from the CF mailing list

**Comment by davidhassell** [comment]
In the light of the point made by @DocOtak (https://github.com/cf-convention/cf-conventions/issues/221#issuecomment-562369361), I'm happy to drop the idea of sub-directories, and just put the file `conformance.adoc` in the same top-level directory as the other conventions' `*.adoc` files.

The idea of putting the conformance document as an appendix to the main conformance document is tempting, but I think that it should remain separate. This is because (quoting from http://cfconventions.org/Data/cf-documents/requirements-recommendations/requirements-recommendations-1.7.html):

_"This document is intended to be a concise summary of the CF Conventions document. If there are any discrepencies between the two, the conventions document is the ultimate authority."_

The conventions shouldn't contain a summary of itself that may disagree with itself! (Thanks to @RosalynHatcher for highlighting this.)

@marqh Thank you very much for your offer of help with the Travis stuff - much appreciated

**Comment by taylor13** [comment]
I support keeping the conformance and standards documents separate (and I support the rest of above too).

**Comment by erget** [comment]
Done! Merry Christmas. 

In summary:
- [x] [Import Conformance doc with history](https://github.com/cf-convention/cf-conventions/commits/master/conformance.adoc)
- [x] [Update `.travis.yml` to autobuild and deploy to gh-pages](https://github.com/cf-convention/cf-conventions/commit/6a2d16afa4d061c123eedb11986ffe5b0a5ab81e)
- [x] [Update links to point back here](https://github.com/cf-convention/cf-convention.github.io/commit/1dde462b71a1424ba38e7f702727e5496b55ab43)
- [x] [Add README to Conformance repo pointing potential contributors back to main repo instead](https://github.com/cf-convention/Conformance/)

We should consider archiving [the Conformance repo](http://github.com/cf-convention/Conformance/) to avoid confusion in the future. I don't have the privileges to do that and think we should discuss it before pulling the rug out from under people's feet.
