### ISSUE TITLE
Geostationary projection & latitude_of_projection_origin

### ISSUE THREAD

**Issue by snowman2** [cf-convention/cf-conventions#246]
Forward from: https://github.com/OSGeo/PROJ/issues/1930

Currently the [geostationary_projection](http://cfconventions.org/cf-conventions/cf-conventions#_geostationary_projection) has the `latitude_of_projection_origin` defined without any defaults provided.

Based on the issue above in PROJ, the projection parameter is not even used for anything and the l`atitude_of_projection_origin` is always assumed to be 0. Are there use cases where the `latitude_of_projection_origin` is not 0 for the `geostationary_projection`?

**Comment by dopplershift** [comment]
Is it physically possible to have a non-zero `latitude_of_projection_origin` and still actually be “geostationary”?

**Comment by erget** [comment]
In practice I don't know of any geostationary data that has a non-zero `latitude_of_projection_origin`. However, this is normally a by-product of rectification. Most geostationary products are produced by satellites that are, in fact, geosynchronous - the satellite doesn't stay consistently above a single point on the Earth, as this would expend a lot of fuel, but rather "wobbles" in a figure-eight about its nominal point. This wobble can actually take the satellite several degrees above and below the 0° latitude line.

Users never notice this because before products go out they are rectified, so it looks like the satellite was always over the same point, but if someone were to use a geostationary projection to provide geolocated but unrectified imagery, some of the products in a timeline might have a non-zero latitude at origin.

I'm not sure what NOAA's doing but my feeling says that PROJ's interpretation is right, so it might be worthwhile to be explicit about this in the Conventions.

**Comment by ajelenak** [comment]
I concur with @erget . Let's keep this attribute.

**Comment by snowman2** [comment]
@erget, I think your explanation is very helpful and makes sense why it is there.

Thoughts on these changes for `geostationary`:
1. Making `latitude_of_projection_origin` an optional attribute with a default of 0
2. Adding a section with notes based on the response by @erget

**Comment by dopplershift** [comment]
That was really helpful, thanks @erget .

**Comment by erget** [comment]
@snowman2 I believe this has been clarified as it's been quiet for >1y but please re-open this if you see the need!
