### ISSUE TITLE
Missing links and references update at the bibliography section

### ISSUE THREAD

**Issue by cofinoa** [cf-convention/cf-conventions#266]
# Title
Missing links and references update at the bibliography section
# Moderator
None
# Requirement Summary
References needs an update and fixing
# Technical Proposal Summary
Better and appropriate references
# Benefits
Who or what will benefit from this proposal?
# Status Quo
The documentation has some broken links and old style references
# Detailed Proposal

These are the changes:
https://github.com/cf-convention/cf-conventions/compare/master...cofinoa:cofinoa-fix-biblio-section
and these are the corresponding commits:
 1. 5c50736bcd1a589cf7d2ae95d4a22aabc35e51df 
 1. 0ea0cc3acaa40a929ad66b8721895140dd5ced14
 1. 465ee756d93da6fff83a1cc2886f5a8e0318d117 (Added @lesserwhirls url for NUG)

With the following major changes:
1. [NETCDF] reference use DOI conforming UNIDATA's citing requirement. https://www.unidata.ucar.edu/community/index.html#acknowledge
1. [NUG] reference pointed to a broken link. Now points to a valid link ~and the right version (4.4.1.1) and release date has been added~
1. [OGC_WKT-CRS] updated link and doc id
1. [OGP-EPSG_GN7_2] update link and reference to last version form september 2019. 
1. [SCH02] DOI link added
1. [Snyder] URL it's broken. Added link to pdf document. Added DOI (but it forwards to broken link at USGS, we should just left the DOI number and remove link?)
1.  [UDUNITS] same as [NETCDF]
1. Some extra white spaces has been removed.

**Comment by lesserwhirls** [comment]
This is great! I would only add that we (mostly @WardF) have been working on breaking out the NUG from the netCDF-C/C++ documentation, and it is currently available at:

https://www.unidata.ucar.edu/software/netcdf/documentation/NUG/

The hope is that it will be useful beyond a language agnostic description of netCDF (the data model, file format specification, best practices, etc.), which is critical on its own, but also serve as an entry point for community advancement of netCDF in general.

**Comment by JonathanGregory** [comment]
Dear all

Most of the updates to the bibliography prepared by @cofinoa have already been implemented. Since it's two years since he opened this, as a `defect`, we can implement the rest. I have prepared [PR 455](https://github.com/cf-convention/cf-conventions/pull/455) to do this, namely

* Use DOIs as the links for `NetCDF` and `UDUNITS`.
* Add the DOI for `SCH02`.
* Revise the link for ESPG Guidance Note 7 Part 2. For this one, I've put the link to the ESPG Guidance Note as a whole, for future-proofing, instead of a link directly to the latest version of Part 2.

In addition, I have

* Deleted the bibliography entry for `OGC-EPSG`, because it's never used in the conventions document.
* Use the DOI as the link for `IEEE_754`, which was given in the text.
* Delete the DOIs in the text, because they are used as the links, so we don't need to see them as well (the document was inconsistent about this).
* Used _italic_ for the journal name in `CFDM`, to match `SCH02`.

Please could someone check this and merge if OK?

Thanks

Jonathan

**Comment by larsbarring** [comment]
This is looking good, one small comment though: Despite what they (IEEE) themselves suggest, I think that we should change this slightly:

[IEEE_754] [IEEE Standard for Floating-Point Arithmetic](https://doi.org/10.1109/IEEESTD.2019.8766229), in IEEE Std 754-2019 (Revision of IEEE 754-2008), ~~vol., no., pp.1-84,~~ 22 July 2019, doi: 10.1109/IEEESTD.2019.8766229.

**Comment by larsbarring** [comment]
Closing this as resolved via PR #455
