### ISSUE TITLE
Unnecessary dimensions on some examples

### ISSUE THREAD

**Issue by cofinoa** [cf-convention/cf-conventions#272]
# Title
Unnecessary dimensions on some examples.
# Moderator
@JonathanGregory 
# Requirement 
SummaryIn some examples where only string type is been used, there is a dimension name_strlen which it's unnecesary.
# Technical Proposal Summary
Remove them
# Benefits
Less confusing
# Status Quo
Discussion of the current state CF and other standards.
# Detailed Proposal
Those unnecessary dimensions has been removed in the PR #268

**Comment by JonathanGregory** [comment]
Thanks for opening this issue. As I said in https://github.com/cf-convention/cf-conventions/pull/268, the changes look fine to me. The dimensions are unnecessary because the examples concerned have been changed from character arrays to strings. They are all in Appendix H.
This is a defect issue because it doesn't materially change the convention. It simply corrects the document. It will be approved by default if no-one objects within three weeks.

**Comment by JonathanGregory** [comment]
I have merged the pull request. Thanks for making this correction, Antonio @cofinoa.
