### ISSUE TITLE
Some labels of examples contain "Example" so that their label in the list of examples contains "Example" (affects four examples)

### ISSUE THREAD

**Issue by neumannd** [cf-convention/cf-conventions#286]
# Title
Some labels of examples contain "Example" so that their label in the list of examples contains "Example" (affects four examples)

# Moderator
@user

# Requirement Summary
The list of examples lists all examples of the CF Conventions. The names/labels of all examples should be displayed in a consistent manner.

# Technical Proposal Summary
Remove "_example X.Y, _" from the label of four examples listed in the list of examples.

# Benefits
Consistency of the list of examples

# Status Quo
In this list, four examples have "_example X.Y, _" in their label. All other examples do not have it.

# Associated pull request
#417 

# Detailed Proposal
The list of examples lists all examples of the CF Conventions. The names/labels of all examples should be displayed in a consistent manner. In this list, four examples have "_example X.Y, _" in their label. All other examples do not have it. I suggest to remove "_example X.Y, _" from the label of four examples listed in the list of examples.

**Comment by davidhassell** [comment]
This seems fine to me, as clearly seen in the "List of Examples" near the top of the [conventions document](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html).

**Comment by taylor13** [comment]
Mmmm.... do you mean the suggested edit "seems fine to me" or do you mean the document as it now stands seems fine.  Like @neumannd I think all the entries in the List of Examples at the top of the conventions document should be consistent and *not* repeat the table number.

I would note that in the "List of Tables" (just above the "List of Examples"), one of the tables listed includes "Table  D.1" in its title, which is also inconsistent with the other tables listed.  I think this should also be made consistent.

**Comment by davidhassell** [comment]
Ah - good point. I meant that the @neumannd's suggested edits are good. I also agree with updating the table titles, as @taylor13 suggests

**Comment by davidhassell** [comment]
Hello @neumannd,

I think that there are no problems with your PR, but would you consider updating it as per @taylor13's [suggestion](https://github.com/cf-convention/cf-conventions/issues/286#issuecomment-713683913) regarding the table D.1 title?

I think we can then get this merged.

Thanks.

**Comment by neumannd** [comment]
@taylor13 @davidhassell Excuse me that I did not react on the comments. Somehow this got lost. Instead of

* changes from the old PR (Example H.1, Example H.8, Example 5.7, Example 5.13)
* change proposed by @taylor13 (Table D.1)
* new changes; removed these duplicate mentions of examples/table
   * Example I.1
   * Table I.1
   * Table I.2
* other changes:
   * "Example 8.7" was not in the list of tables
   * `_` replaced by `-` in label of Example 8.7

**Comment by davidhassell** [comment]
Hi @neumannd  - thanks for re-finding this! I shall try to generate a new copy of the doc to see how they look ...

**Comment by davidhassell** [comment]
Hi - I have built the html based in PR #418 

* http://www.met.rdg.ac.uk/~david/cf-conventions.html
* http://www.met.rdg.ac.uk/~david/cf-conventions.pdf

and it looks good - thanks. There are a couple of things that I spotted:

Apart from the tables `D.1`, `I.1`, and `I.2`, which do not have those labels next to their captions. I presume that this was  why they were hardwired into the captions before. I tried adding a `[caption="Table D.1. "]` line but that had no effect, presumably because tables are not caption-able entities (?). I'm sure there's something that can be done here, but I don't know what ...

Also, the modified examples in the summary have their title in quotes (e.g. `5.7. "Lambert conformal projection"`).

**Comment by neumannd** [comment]
@davidhassell I added the captions in PR #419 which belongs to issue #418

**Comment by neumannd** [comment]
The conventions document generated by PR #419 has duplicate labels and the PR to this issue (#417) has no labels for these tables. If both PRs are merged, the table captions should be correct.

I submitted to separate PR and issues for this because the changes in issue #418 do not fit the the title of this issue.

**Comment by neumannd** [comment]
@davidhassell @taylor13 Can we proceed with this (and the other to issues solving related issues)?

**Comment by taylor13** [comment]
I'm a little lost on status and PRs, but I think there was no disagreement on what should be done, so if @davidhassell signs off, yes, please proceed.

**Comment by neumannd** [comment]
@taylor13 @JonathanGregory Please excuse me for the late reply. I overlooked the comments.

Regarding my name: I married in 2020 and changed my last name from "Neumann" to "Heydebreck". Did not think about mentioning it here ;-) .

If there are no objections, could someone merge #417 ?

**Comment by JonathanGregory** [comment]
Dear @neumannd 

Thanks for reminding us. Actually I looked at [PR 417](https://github.com/cf-convention/cf-conventions/pull/417) and [PR 419](https://github.com/cf-convention/cf-conventions/pull/419) just yesterday. It looks like they modify similar pieces of text. Are they compatible? Do they both need to be merged?

Cheers

Jonathan

**Comment by neumannd** [comment]
@JonathanGregory I think that they do not contradict each other. When I created them I had the feeling that they should be slit in two parts. I am not sure why. That's too long ago. Maybe because someone might object #417 . Not sure.

**Comment by JonathanGregory** [comment]
Dear @neumannd

In https://github.com/cf-convention/cf-conventions/pull/417, if you delete "Table D.1" from the caption of the table, it won't appear in the rendered text, unlike other tables - isn't that the case? It's apparently treated differently from other tables, which indeed don't have "Table XXX" in their caption, because it's "unusually" long, according to the comment in the asciidoc. Maybe we can fix the problem by putting some of the caption in ordinary text, and deleting the hack using a 1-pixel transparent image. For instance, the table caption could be just "Consistent sets of attributes", if it is possible to insert some text after the caption and before the table to say "These sets of attribute values are needed in defining the ocean sigma coordinate, the ocean s-coordinate, the ocean_sigma over z coordinate, and the ocean double sigma coordinate". Is that possible in asciidoc?

Cheers

Jonathan

**Comment by neumannd** [comment]
@JonathanGregory :  You are right. I forgot that. #417 seems to clean up the captions and #419 seems to use the `caption` field consistently. Both merge requests should be merged in combination. I do not remember why I did it this way.

**Comment by JonathanGregory** [comment]
For the record, as well as deleting "Example _whatever_" from the titles of four examples, [PR 417](https://github.com/cf-convention/cf-conventions/pull/417) also

*  Deletes "Title _whatever_" from the titles of three tables.
*  Inserts one example into the list of examples.
*  Inserts a missing `.` into the label of one example.

I will merge it and [PR 419](https://github.com/cf-convention/cf-conventions/pull/419), since these are defects and no-one objects to the correction. Thanks, @neumannd.
