### ISSUE TITLE
Introduce the value "grid_id" for the variable attribute cf_role

### ISSUE THREAD

**Issue by LorenzoCorgnati** [cf-convention/cf-conventions#300]
# Title
Introduce the value "grid_id" for the variable attribute cf_role. It will describe gridded data, since the values allowed do not take into account this kind of data.
# Moderator
@roy-lowry 
# Moderator Status Review [last updated: YY/MM/DD]

# Requirement Summary
In order to describe gridded data (e.g High Frequency Radar surface current data) I propose to add the value "grid_id" along the allowed ones (timeseries_id, profile_id, trajectory_id) for the variable attribute cf_role.
# Technical Proposal Summary

# Benefits
Providers and managers of gridded data will benefit of this enhancement.
# Status Quo
The allowed values (timeseries_id, profile_id, trajectory_id) for the cf_role variable attribute do not suit gridded data.
# Associated pull request

# Detailed Proposal
Please see above.

**Comment by roy-lowry** [comment]
Not sure I was asked to take on the role of moderator but if there are no objections I'll do it.

CF was initially created for gridded data. The cf_role attribute was added when CF was extended to deal with discrete sampling geometries. @LorenzoCorgnati is asking the question whether gridded data should be explicitly annotated through the addition of cf_role='grid_id' or should the existing practice of simply leaving the cf_role attribute out continue. I feel inclusion is possibly better practice, but the existing practice has the advantage of backward compatability - so much so that if a value of  'grid_id' is allowed then this must be considered equivalent to the cf_role attribute being omitted.

Anyone any thoughts?

**Comment by JonathanGregory** [comment]
I suggest that this issue should be left until the relate issue https://github.com/cf-convention/cf-conventions/issues/299 is decided.

**Comment by roy-lowry** [comment]
@JonathanGregory Agreed.

**Comment by roy-lowry** [comment]
See discussion on related issue #299
