### ISSUE TITLE
Note in CONTRIBUTING for Conventions: Moderator should keep summary up to date and post in comments when updates so that people get pinged

### ISSUE THREAD

**Issue by erget** [cf-convention/cf-conventions#306]
This was agreed at the 2020 Community Meeting and has since been enshrined in practice but not in text. I will propose a text that makes this part of the tasks for which a moderator takes responsibility.

**Comment by erget** [comment]
Dear community, this minor change to CONTRIBUTING.md comes from the CF 2020 meeting at which it was proposed. I've been slow following it up, obviously. Is anybody interested in supporting or opposing this minor change?

**Comment by erget** [comment]
@sadielbartholomew thanks for having a look at the MR - can I understand this as support for the proposal in general?

If that's the case, as this is a clarification on GitHub of agreed procedure I will consider this supported and merge in 3w unless somebody objects.

**Comment by sadielbartholomew** [comment]
> can I understand this as support for the proposal in general?

Yes, I do support it. Sorry if I wasn't fully clear! The approval was for both the idea and the implementation here.

Though I would mention that going forward it would be ideal if we could automate some of this so that 'moderator' may eventually make way to some sort of automated process, e.g. that suggested in cf-convention/discuss#88 (admittedly by myself, but with some agreement expressed there by others already), when we can get something along those lines built. Something to initiate at the hackathon, perhaps!

**Comment by erget** [comment]
Agree, that would be a cool hackathon topic.

I'll merge the corresponding PR on 2022-05-11.

**Comment by JonathanGregory** [comment]
Dear Daniel @erget and @sadielbartholomew 

This looks fine to me as well. Thanks

Jonathan
