### ISSUE TITLE
https://github.com/cf-convention/cf-conventions/pull/331 not implemented in http://cfconventions.org/cf-conventions/cf-conventions.html

### ISSUE THREAD

**Issue by JonathanGregory** [cf-convention/cf-conventions#334]
I notice that the changes made by the merged pull request https://github.com/cf-convention/cf-conventions/pull/331 (the recently agreed changes to time coordinates and calendar definitions) do not appear in the current working version http://cfconventions.org/cf-conventions/cf-conventions.html. Should this have happened automatically?

**Comment by erget** [comment]
Yes, there is some magic going on between the 2 repositories that I don't quite understand. @ethanrd @painter1 @dblodgett-usgs (I my be forgetting somebody) and I had discussed this sometime... Last year? And we ended up documenting it [here](https://github.com/cf-convention/cf-conventions#latest-spec-build) but that seems to not correctly describe what's happening now.

**Comment by JonathanGregory** [comment]
Thanks, @davidhassell  and @erget. Would this be related to https://github.com/cf-convention/cf-conventions/issues/297, which is one of the outstanding issues that Daniel identified? Might @sadielbartholomew be able to help?

**Comment by erget** [comment]
@JonathanGregory yes, I believe so.

**Comment by ethanrd** [comment]
Right! We haven't fully moved to GitHub Actions. The automatic build still targets Travis-CI. However, it looks like Travis-CI transitioned the travis-ci.org domain over to the travis-ci.com domain (in June I believe) but we didn't switch CF over to use travis-ci.com.

Quickest fix, I believe, would be to transition the Travis config to use travis-ci.com. It sounds like it is supposed to be an easy transition. The other option is to make the move to GitHub Actions, but I suspect that would take a bit more work.

I'm going to take a quick look at what it takes to migrate to travis-ci.com. I'll report back shortly.

**Comment by ethanrd** [comment]
Well, my quick look wasn't quite long enough. There are limitations, of course, on the [free plan](https://docs.travis-ci.com/user/billing-overview/#free-plan) and some paperwork involved to get on the [open source plan](https://docs.travis-ci.com/user/billing-faq/#what-if-i-am-building-open-source) (which has different limitations).

Not sure if its worth digging much more since we know we want to move to GitHub Actions. In the meantime, we could "hand" build the docs and push to the gh-pages branch. Not ideal but it could get us through till someone has time to work on the move to GH Actions.

**Comment by sadielbartholomew** [comment]
Hi all, sorry for the delay in replying to this - it got lost somewhat in my busy GitHub notifications inbox.

> Not sure if its worth digging much more since we know we want to move to GitHub Actions. 

I'd be inclined to agree with that, best move straight to Actions because from my experience with migrating and extending the CI for other libraries, it is not too difficult. Saying that, I don't know much (yet) about the current setup and how complex it may be, unlike you @ethanrd!

> Not ideal but it could get us through till someone has time to work on the move to GH Actions.

> Might @sadielbartholomew be able to help?

@JonathanGregory mentioned this in an email thread and I said I would be happy to volunteer to do it, and spend a bit of time helping out with technical CF issues generally, having done the migration before for e.g. cf-python and cfdm, though Jonathan suggested wisely that some other website and conventions document issues should be prioritised first, namely (taken verbatim from the email):

> conventions
> 266 missing links and reference updates
website
> 142 missing links

I will have a look and estimate how quickly it will take for those to be sorted. If it might take a while, which seems unlikely, maybe:

> In the meantime, we could "hand" build the docs and push to the gh-pages branch. Not ideal but it could get us through till someone has time to work on the move to GH Actions.

is indeed the best plan. But if not, I can get started migrating to Actions soon. I've been informed that @lesserwhirls had plans to do the migration in the past - is this still on the cards? If so, we could make a joint effort to get it done, though if you don't have the bandwidth I am happy to do the conversion myself.

**Comment by lesserwhirls** [comment]
I believe I had volunteered to do this last year...I do apologize.

I can take a look at this first thing tomorrow. It should not be too bad (famous last words) given that 1) the [building part is already done](https://github.com/cf-convention/cf-conventions/blob/master/.github/workflows/check_adoc_build.yml), and 2) we can copy [most of the release logic from the travis build](https://github.com/cf-convention/cf-conventions/blob/da60f6308a2b593fd7b8d7b7785efb71bb0178b9/.travis.yml#L25-L52) into the same GitHub Actions workflow or a new release only workflow.

**Comment by lesserwhirls** [comment]
GitHub was having issues yesterday, which held up getting this out. However, I believe I have it all working now in PR cf-convention/cf-conventions#335.

**Comment by sadielbartholomew** [comment]
Great work @lesserwhirls! That was quick. @erget, would you like me to help at this point by reviewing Sean's PR #335? Otherwise I can get started in earnest tackling the initial items on @JonathanGregory's priority list of current CF technical issues.

**Comment by erget** [comment]
My thanks also to @lesserwhirls and @sadielbartholomew - yes, if you could review the PR that would be very useful.

**Comment by JonathanGregory** [comment]
Thank  you very much for working on this, Sean @lesserwhirls and @sadielbartholomew. Jonathan

**Comment by JonathanGregory** [comment]
Fixed in https://github.com/cf-convention/cf-conventions/pull/335 by @lesserwhirls, thanks.
