### ISSUE TITLE
Use Kanban to visualise proposal status

### ISSUE THREAD

**Issue by erget** [cf-convention/cf-conventions#361]
This was proposed as an action at the CF User Meeting in 2020. Is anybody interested in working on this? I would join them at the 2022 User Meeting to hack on it!

**Comment by sadielbartholomew** [comment]
Hi Daniel, one question on this: quite what form of Kanban is intended here? Would GitHub Projects suffice, since that can be used effectively as a Kanban board I believe, and it is very accessible directly here in GitHub which we already use for most things relating to discussion, organisation maintenance of the CF Conventions?

I guess there are some points in the CF Meeting 2020 notes relating to this proposal. Would you mind pointing me /  us generally to those so I can see a bit more? Thanks.

**Comment by erget** [comment]
@sadielbartholomew yes, I think GitHub Projects would be the tool of choice - it's good to have everything in one place. There's [a project associated with this issue](https://github.com/orgs/cf-convention/projects/1) that contains the follow-up to the 2020 meeting - you can find everything that I noted down at the time there. As always, your ideas a very welcome :)

**Comment by JonathanGregory** [comment]
Dear Daniel @erget, @sadielbartholomew 

Is there a prospect of some progress on this in the near future? If not, I suggest we could close it as `dormant` for now, since it's been quiet for a couple of years. It could be reopened later, of course.

Best wishes

Jonathan

**Comment by erget** [comment]
@JonathanGregory this was used at the 2022 meeting and I think it was useful in the context of hackathons but I haven't gotten the impression it's been a feature in hot demand for the CF organization as a whole between hackathons. It's easy enough to setup that we might use it next time but I don't think that it's something that we need to pursue at this time for moving the issues - we seem to have achieved good flow as it is for the moment. Happy to close this now.
