### ISSUE TITLE
Clarify the intention of standard names

### ISSUE THREAD

**Issue by JonathanGregory** [cf-convention/cf-conventions#366]
In https://github.com/cf-convention/vocabularies/issues/132 @jonathanlilly has pointed out that the current text of section 3.3 might appear to mean that a given `standard_name` can appear only once in any file. The text follows the description of `long_name`, whose usage is stated to be "completely ad-hoc." It continues

> For some applications it would be desirable to have a more definitive description of the quantity, which would allow users of data from different sources (some of which might be models and others observational) to determine whether quantities were in fact comparable. For this reason an optional mechanism for uniquely associating each variable with a standard name is provided.

Also it's written with "would" as though standard names are hypothetical, because this text was written at the start of CF when they were a new idea. I propose that we replace the above text with the following, in which I have put new words in **bold**:

> For **many** applications it **is** desirable to have a more definitive description of the quantity, which **allows** users of data from different sources (some of which might be models and others observational) to determine whether quantities **are** in fact comparable. For this reason **each variable may optionally be given a "standard name", whose meaning is defined by this convention.**

Comments are welcome. I believe that this does not change the intended meaning of the convention, but only clarifies the text. Therefore it can be treated as a remedy for a defect, so this proposal will be accepted in three weeks (on 2nd June) if there are no objections.

Jonathan

**Comment by davidhassell** [comment]
Dear Jonathan, Looks good - no objection from me. Do you want to write a Pull Request?
Thanks,
David

**Comment by larsbarring** [comment]
With reference to the use case provided in [convention/discuss#155](https://github.com/cf-convention/discuss/issues/155) --- two variables both having ``standard_name = "time"``, where one is a time average of the other and thus has ``cell_method = "time: mean"`` --- might it be useful to include a reference to this CF mechanism? Something like: 
> For **many** applications it **is** desirable to have a more definitive description of the quantity, which **allows** users of data from different sources (some of which might be models and others observational) to determine whether quantities are in fact comparable. For this reason **each variable may optionally be given a "standard name", whose meaning is defined by this convention, possibly with further details given in the cell methods**.

**Comment by JonathanGregory** [comment]
Dear @larsbarring 

Yes, I take the point, which is also partly what I replied to @jonathanlilly. I'd prefer to say something more general than just referring to `cell_methods`. Would this be OK:

> For **many** applications it **is** desirable to have a more definitive description of the quantity, which **allows** users of data from different sources (some of which might be models and others observational) to determine whether quantities are in fact comparable. For this reason **each variable may optionally be given a "standard name", whose meaning is defined by this convention. There may be several variables in a dataset with any given standard name, and these may be distinguished by other metadata, such as coordinates (Section 4) and `cell_methods` (Section 7.3).**

Jonathan

**Comment by larsbarring** [comment]
Yes, this is much better! Thanks /Lars

**Comment by jonathanlilly** [comment]
Should long_name and comments also be mentioned as ways of
distinguishing among different variables with the same standard_name?

Is long_name, in contrast, expected to be unique within a given dataset,
and if so should this be mentioned in 3.2?

Jonathan L.

On May 13, 2022, Github Notifications ***@***.***> wrote:
> Yes, this is much better! Thanks /Lars
>

—
Reply to this email directly, view it on GitHub <https://github.com/cf-
convention/cf-conventions/issues/366#issuecomment-1125877544>, or
unsubscribe <https://github.com/notifications/unsubscribe-
auth/ABWKBAUWSRLLC32BGOEB6TLVJYSXPANCNFSM5VYLTSSA>.
You are receiving this because you were mentioned.Message ID: <cf-
***@***.***>

**Comment by larsbarring** [comment]
Long_name and comments are not managed or mandated by the CF Conventions, neither regarding their content or being present at all. A data producer or user may of course use them to that effect (for my own personal use I often think of a long_name as way to provide a succinct and generic plot title or similar.) In principle the CF Conventions are not linked to the netCDF file format, but in practice this is often case. And in netCDF files the variable name is the key unique identifier that distinguish one variable from another.

**Comment by jonathanlilly** [comment]
I see.  Thanks a lot for the clarification!

On May 13, 2022, Github Notifications ***@***.***> wrote:
> Long_name and comments are not managed or mandated by the CF
> Conventions, neither regarding their content or being present at all.
> A data producer or user may of course use them to that effect (for my
> own personal use I often think of a long_name as way to provide a
> succinct and generic plot title or similar.) In principle the CF
> Conventions are not linked to the netCDF file format, but in practice
> this is often case. And in netCDF files the variable name is the key
> unique identifier that distinguish one variable from another.
>

—
Reply to this email directly, view it on GitHub <https://github.com/cf-
convention/cf-conventions/issues/366#issuecomment-1126037940>, or
unsubscribe <https://github.com/notifications/unsubscribe-
auth/ABWKBARROUVRWJY6GRQ4MZTVJZHZPANCNFSM5VYLTSSA>.
You are receiving this because you were mentioned.Message ID: <cf-
***@***.***>

**Comment by JonathanGregory** [comment]
Three weeks have elapsed, so this change is agreed. I have prepared https://github.com/cf-convention/cf-conventions/pull/368 to implement it. Please could someone check it and merge? Thanks.

**Comment by jonathanlilly** [comment]
Hi David,

Just to clarify, since there are multiple Jonathans involved, were you
asking me to write a Pull Request?  Jonathan Gregory has already written
some text and I'm not sure if this was meant for him.

Jonathan (Lilly)

On May 12, 2022, Github Notifications ***@***.***> wrote:
> Dear Jonathan, Looks good - no objection from me. Do you want to write
> a Pull Request?
>  Thanks,
>  David
>

—
Reply to this email directly, view it on GitHub <https://github.com/cf-
convention/cf-conventions/issues/366#issuecomment-1125044804>, or
unsubscribe <https://github.com/notifications/unsubscribe-
auth/ABWKBARL4P6TR4AAKLMZZ2DVJUGRBANCNFSM5VYLTSSA>.
You are receiving this because you were mentioned.Message ID: <cf-
***@***.***>

**Comment by davidhassell** [comment]
Hi Jonathan (Lilly) - sorry for the confusio! I think we're all OK here - I was replying to the other Jonathan, who did indeed write a PR that has been merged, so it all worked out in the end.

Thanks,
David
