### ISSUE TITLE
Asciidoc and Markdown style guides?

### ISSUE THREAD

**Issue by erget** [cf-convention/cf-conventions#373]
It would be nice to have a style guide for the documents that we take care of. Perhaps a topic for the upcoming user meeting and even a  hackathon? 🤔 I'll contribute if anybody else thinks this is a good idea.

As proposed in https://github.com/cf-convention/discuss/issues/152#issuecomment-1098142727

**Comment by davidhassell** [comment]
Great idea. Lets add that to teh existing scheduled hackathon: https://github.com/cf-convention/discuss/issues/152#issuecomment-1098142727

**Comment by sadielbartholomew** [comment]
I also agree, this could be very useful. Though I would recommend that we refer to an existing guide/standard, rather than writing our own (that may have been the intention anyway, not sure!). I am thinking a clear and concise (enough) page of style guidance such as the Google style guides, e.g. [here for Markdown](https://google.github.io/styleguide/docguide/style.html) (though they don't seem to have anything covering Asciidoc), would work well.

And if there are auto-formatting tools available that we can utilise, even better, though I have not head of one for Markdown, at least. We can do a survey to see if anything exists, of course.

**Comment by erget** [comment]
For Asciidoc @dnowacki-usgs found [this](https://asciidoctor.org/docs/asciidoc-recommended-practices/) which at first blush looks good to me.

**Comment by erget** [comment]
After agreeing on one we might need a separate task to implement it to start.

One element I could imagine is taking a look at the use of monotype - in 5.6.1 I just noticed that we have some places where attributes are in normal type, rather than monotype, and we'd likely improve readability by changing that.

**Comment by erget** [comment]
Same in following chapters, e.g. In chapter 6 you've got some naked URLs.

**Comment by erget** [comment]
And "fixed_angle_axis" in table F.1 has formatting issues - it's bolded, not monotyped.

**Comment by erget** [comment]
Same thing with sweep_angle_axis...

**Comment by erget** [comment]
H.3 - in the caption of the example we'd benefit from some monotyping.

**Comment by erget** [comment]
Consistent number of linebreaks between paragraphs?

**Comment by erget** [comment]
Eliminate trailing whitespace?

**Comment by jesusff** [comment]
The lack of monotypes at some places is due to a trailing space right before the ending mark.

Does it make sense to also try to stick to a single way of writing bold and monotype together? There is currently a mix of 
```
**`bold monotype`**
```
and
```
`**bold monotype**`
```
A single way would ease automatic location of errors such as extra space.

**Comment by davidhassell** [comment]
Hello, I have had a quick look at the two style guides that have been mentioned (https://asciidoctor.org/docs/asciidoc-recommended-practices and https://google.github.io/styleguide/docguide/style.html), but don't have a string opinion either way. 

If I had to have an opinion, I might prefer the Google guide, simply because a) it doesn't contain any "TODOs", and b) it's shorter!

Thanks, David

**Comment by jesusff** [comment]
Yes, they look good. There are some TODO parts, though. E.g. here there is no decision on monotype:

https://asciidoctor.org/docs/asciidoc-recommended-practices/#literal-text

but I think for this specific matter we clearly went for backticks to represent them. There is no plus sign representation for monotypes in the whole document.
