### ISSUE TITLE
Update some links and references

### ISSUE THREAD

**Issue by larsbarring** [cf-convention/cf-conventions#391]
In the HTML version of the Conventions document the "keywords" are shown as expected in the reference list, but not in the PDF version. See this example:

HTML:

    black_small_square [NetCDF][ NetCDF Software Package](http://www.unidata.ucar.edu/netcdf/index.html) . UNIDATA Program Center of the University Corporation for Atmospheric Research

PDF:

    black_small_square [] [NetCDF Software Package](http://www.unidata.ucar.edu/netcdf/index.html) . UNIDATA Program Center of the University Corporation for Atmospheric Research .

------

Another small thing that I just came across: The link in the [Snyder] reference item should be updated to read
"https://pubs.er.usgs.gov/publication/pp1395" (or is this a separate issue + PR?)

PS:

... and a simple typo in the reference item just above:

    [SCH02] C Schaer, D Leuenberger, and O Fuhrer. 2002. “ A new terrain-following vertical coordiante formulation for atmospheric prediction models ”. Monthly Weather Review . 130 . 2459-2480

**Comment by JonathanGregory** [comment]
Thanks for this defect issue of last September, @larsbarring. I see that the appearance of the keywords and little black squares have been corrected in the bibliography of the [pdf of the current working version](http://cfconventions.org/cf-conventions/cf-conventions.pdf) but the Synder link and the typo you found have not been fixed. I have therefore prepared [PR 441](https://github.com/cf-convention/cf-conventions/pull/441) to make these corrections. I will merge it myself now (hoping I've got it right), because far more than three weeks have passed since you raised the issue. Jonathan

**Comment by larsbarring** [comment]
Following the [comment](https://github.com/cf-convention/cf-conventions/issues/445#issuecomment-1679692204) by @JonathanGregory  that
> ... I note that the Snyder map projection document [...] has a DOI, which would be more future-proof, viz https://doi.org/10.3133/pp1395.

I am reopening this issue and will shortly create a new PR to replace the current link with the DOI.
