### ISSUE TITLE
Always use "strictly monotonic" when describing coordinate variables rather than simply "monotonic"

### ISSUE THREAD

**Issue by ethanrd** [cf-convention/cf-conventions#423]
# Coordinate variables must be strictly monotonic not just monotonic, clarify in text

# Moderator
@user

# Requirement Summary
The CF conventions document sometimes describes coordinate variables as "monotonic" rather than "strictly monotonic". It should always use "strictly monotonic".

Strictly monotonic means always increasing or decreasing without any identical values, whereas "monotonic" allows for multiple identical values (never increasing or never decreasing).

The [NUG defines a coordinate variable](https://docs.unidata.ucar.edu/nug/current/best_practices.html#bp_Coordinate-Systems) as "strictly monotonic (values increasing or decreasing)" and [again](https://docs.unidata.ucar.edu/nug/current/netcdf_data_set_components.html#coordinate_variables) as "numeric and strictly monotonic (all values are different and either increasing or decreasing)".

# Technical Proposal Summary
Update language in various locations to always use "strictly monotonic".

# Benefits
Who or what will benefit from this proposal?

# Status Quo
Current use of "monotonic" instead of "strictly monotonic" can cause confusion.

# Associated pull request
PR #424

# Detailed Proposal
See PR #424

**Comment by JonathanGregory** [comment]
Dear @ethanrd 

Thanks for clarifying this. I support it. Actually I had not realised, before reading the PR, that we had stated that time must be strictly increasing in DSG features with a time dimension. That's the only place we require a particular order. Is this extra requirement also included in the conformance document?

In the definition in chapter 1, I think we could be slightly clearer than "all values are different and either increasing or decreasing", since the aim of these changes is clarity! I'd suggest "all values are different, and they are arranged in either consistently increasing or consistently decreasing order."

Best wishes

Jonathan

**Comment by ethanrd** [comment]
Hi @JonathanGregory - I like your suggestion for clarifying the coordinate variable definition in chapter 1. I will add that to the PR.

I also wonder if a fuller discussion of strict monotonicity might be in order, including why it is important (strictly monotonic functions are invertible which is important for transformations and interpolations). It would be relevant to several sections that discuss strict monotonicity not related to a coordinate variable. For instance, the chapter on DSGs and the appendix on Parametric Vertical Coordinates require strict monotonicity for some auxiliary coordinate variables and the chapter on Lossy Compression by Coordinate Subsamples requires strict monotonicity for tie point index variables.

**Comment by ethanrd** [comment]
I also wonder if the DSG section needs closer review as I'm not sure why time has a strict monotonicity requirement for timeseries and trajectory but vertical doesn't for profiles. Also, though the DSG chapter implies that monotonicity is required whether using an auxiliary coordinate variable or a coordinate variable, the DSG appendix mention of monotonicity appear to only be about coordinate variables.

And, in terms of specifying increasing or decreasing, there is one mention of monotonicity outside of DSGs that also mentions the ordering. In the "Ocean sigma over z coordinate" section of Appendix D where it says it is "either increasing or decreasing [as] indicated by the `positive` attribute".

**Comment by JonathanGregory** [comment]
I agree that the vertical coordinate in profile features should be strictly monotonic. The text says it is "ordered", which probably implies monotonic, but it would be better to use the same word as for timeseries. I think that the logic for requiring strict monotonicity within a feature is that, in the orthogonal multidimensional representation, the coordinate values would be in coordinate variables, and thus required to be strictly monotonic. The DSG representations are _logically_ equivalent to the orthogonal multidimensional representation. The data model does not distinguish them. Therefore the requirement should be the same. That's also why I'm concerned that the chapter 9 requires time to be increasing, rather than decreasing. We don't make that requirement usually of a time coordinate variable (though of course it usually is increasing). We should not impose this requirement for the  orthogonal multidimensional representation, even if we keep it for the other representations in chapter 9.

The values of parametric coordinate variables must be strictly monotonic, like any coordinate variable. The elements of formula terms with the vertical dimension have to correspond to those of the parametric coordinate variable, so there can't be any requirement on them. They may not be all be unique even.

I agree that monotonicity is necessary for inversion, which is one reason to require it for coordinate variables. Another is simply that software often assumes monotonicity, and it's best to avoid problems if we can (that's one of our design principles). You're right that it would be helpful to explain the reasons for the requirement.

**Comment by taylor13** [comment]
I support the proposed changes as discussed above.  Thanks @ethanrd and @JonathanGregory for cleaning up these points.

**Comment by larsbarring** [comment]
[bump] @ethanrd 
I, too, support these changes. Could the [associated PR](https://github.com/cf-convention/cf-conventions/pull/424) be finalised to get the changes into the next version?

**Comment by JonathanGregory** [comment]
Thanks for preparing and updating the pull request, @ethanrd. I'll merge it now. Jonathan
