### ISSUE TITLE
Single data values taken over spatial/temporal range.

### ISSUE THREAD

**Issue by lhmarsden** [cf-convention/cf-conventions#429]
I often work with data collected from ice cores. In many cases, the ice core is split into sections and melted. A single measurement is taken for each section (e.g. the salinity of the ice core) and one can analyse how these measurements vary with 'depth' in the ice. 

Depth       Salinity
0-10 cm    2.5%
10-20 cm  2.8%
20-30 cm  2.9%
30-37 cm  3.1%

I plucked those values out of the air, they are probably not realistic!

How should I structure a CF-NetCDF file where each value covers a depth range rather than a discreet depth? As far as I am aware, there is not a minimum_depth and maximum_depth standard name. I am not what the best, most machine understandable solution should be.

I suspect this use case could be relevant to many scenarios - sediment cores, values averaged over a depth range in sea water, values averaged over a time range etc.

**Comment by Armin-RS** [comment]
Hi,

I would think that a "z" and a "z_bounds" variable would be a CF way of encoding this.


z = 5, 15, 25, 33.5cm
z_bounds = (0, 10), (10, 20), (20,30), (30,37)

dims:
time =4
bnds = 2

z(time)
z:units="cm"
z:bounds =z_bounds

z_bounds(time,bnds)


Would that work for you ?


Best regards,
Armin Rauthe-Schöch



-----Ursprüngliche Nachricht-----
Von: Luke Marsden ***@***.***> 
Gesendet: Dienstag, 31. Januar 2023 08:43
An: cf-convention/cf-conventions ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [cf-convention/cf-conventions] Single data values taken over spatial/temporal range. (Issue #429)

I often work with data collected from ice cores. In many cases, the ice core is split into sections and melted. A single measurement is taken for each section (e.g. the salinity of the ice core) and one can analyse how these measurements vary with 'depth' in the ice.

Depth Salinity
0-10 cm 2.5%
10-20 cm 2.8%
20-30 cm 2.9%
30-37 cm 3.1%

I plucked those values out of the air, they are probably not realistic!

How should I structure a CF-NetCDF file where each value covers a depth range rather than a discreet depth? As far as I am aware, there is not a minimum_depth and maximum_depth standard name. I am not what the best, most machine understandable solution should be.

I suspect this use case could be relevant to many scenarios - sediment cores, values averaged over a depth range in sea water, values averaged over a time range etc.

—
Reply to this email directly, view it on GitHub <https://ofcsg2dvf1.dwd.de/fmlurlsvc/?fewReq=:B:JVI2PTk7Nip6MT4iPCplaDE8PTY8PSp/ZWtibXh5fmkxOzhpODw9OTw1Pzk4ND41NWlvOG1qaTo8OjloaWk7aGppPG41ND8/OSp4MT06Ozk9OT08PjgqfWVoMT88WjtkZWNIPDw0PTQ/IT88WjtkZWNJPDw0PTQ/Kn5vfHgxTX5hZWIiXm15eGRpIV9vZGNpb2RMaHtoImhpKm8xOT4qZGhgMTw=&url=https%3a%2f%2fgithub.com%2fcf-convention%2fcf-conventions%2fissues%2f429> , or unsubscribe <https://ofcsg2dvf1.dwd.de/fmlurlsvc/?fewReq=:B:JVI2PTk7Nip6MT4iPCplaDE8PTY8PSp/ZWtibXh5fmkxPD09bmo5aDVtOTtpOThuNTk9NWk7Oj4/aj1pam81OjhvNWo6PD04OCp4MT06Ozk9OT08PjgqfWVoMT88WjtkZWNIPDw0PTQ/IT88WjtkZWNJPDw0PTQ/Kn5vfHgxTX5hZWIiXm15eGRpIV9vZGNpb2RMaHtoImhpKm8xOT4qZGhgMTw=&url=https%3a%2f%2fgithub.com%2fnotifications%2funsubscribe-auth%2fAN5XMXFUWLN66NGHOA5YTIDWVC7BXANCNFSM6AAAAAAUMCX5NE> .
You are receiving this because you are subscribed to this thread. <https://ofcsg2dvf  1.dwd.de/fmlurlsvc/?fewReq=:B:JVI2PTk7Nip6MT4iPCplaDE8PTY8PSp/ZWtibXh5fmkxbm49Pm5obW5uPjlobzpvPzg7Oz84Pm5qP29vPW48bmg1aGo0NWo/Oip4MT06Ozk9OT08PjgqfWVoMT88WjtkZWNIPDw0PTQ/IT88WjtkZWNJPDw0PTQ/Kn5vfHgxTX5hZWIiXm15eGRpIV9vZGNpb2RMaHtoImhpKm8xOT4qZGhgMTw=&url=https%3a%2f%2fgithub.com%2fnotifications%2fbeacon%2fAN5XMXBNWUP3X3SOSBGJWITWVC7BXA5CNFSM6AAAAAAUMCX5NGWGG33NNVSW45C7OR4XAZNFJFZXG5LFVJRW63LNMVXHIX3JMTHF2NPNTM.gif&fmlBlkTk> Message ID: ***@***.***>


----------
Hinweis (DWD): Mindestens eine URL in dieser E-Mail wurde vom Schadsoftware-Erkennungssystem als potentiell gefährlich eingestuft und so umgeschrieben, dass ein Klick darauf diese zunächst auf gefährliche Downloads hin untersucht, bevor Inhalte angezeigt werden. Die Analyse erfolgt ohne menschliches Zutun voll automatisiert. Der Datenschutz ist gewährleistet. Es kann einige Sekunden dauern, bis die Inhalte angezeigt werden.
Der Originalabsender dieser E-Mail ist: ***@***.*** Wenn Ihnen dieser unbekannt ist, so sollten Sie die enthaltenen Links nicht anklicken.

**Comment by lhmarsden** [comment]
This looks like an interesting approach. What would be the variable attributes that I should use for the z_bounds variable?

**Comment by Armin-RS** [comment]
The "z_bounds" variable does not have to have any attributes. It is implied that it has the same units etc. as the "parent" variable "z". 

Probably clearer:

dims:
depth =4
bnds = 2

z(depth)
z:units="cm"
z:bounds = "z_bounds" (I missed the quotation marks above)

z_bounds(depth,bnds)

salinity(depth)
salinity:cell_methods = "depth: mean"

**Comment by Armin-RS** [comment]
See here in the CF Convention: http://cfconventions.org/Data/cf-conventions/cf-conventions-1.10/cf-conventions.html#_data_representative_of_cells

**Comment by lhmarsden** [comment]
Thanks, very helpful!
