### ISSUE TITLE
Update the XML format specification in Appendix B to provide a robust link to the XML schema file

### ISSUE THREAD

**Issue by larsbarring** [cf-convention/cf-conventions#516]
# Title
Update the XML format specification in Appendix B to provide a robust link to the XML schema file
# Moderator
Not yet
# Requirement Summary
If a XML schema definition file (.xsd) is specified in the XML file it has to be available to the software reading the XML file. 
# Technical Proposal Summary
This is one in a string of issues that aims to improve the format of the XML version of the standard name table files, see https://github.com/cf-convention/cf-convention.github.io/issues/457 for background and overview. 

Specifically, this proposal updates [Appendix B](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.11/cf-conventions.html#standard-name-table-format) to include the the robust link implemented through issue https://github.com/cf-convention/cf-convention.github.io/issues/469. It also updates `Example B.1` to account for the recent changes. 
# Benefits
All users of the XML version of the standard name table will be able to more effectively draw on the format specification laid out in Appendix B.  
# Status Quo
This proposal have no bearing on the material content of the CF Conventions.
# Associated pull request
#517 
# Detailed Proposal
Only a small technical change is required:

Current text:
> <standard_name_table
 xmlns:xsi="https://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="**CFStandardNameTable.xsd**">

Note that the boldfaced filename does not have directory specified or is a html link, which means that there is no information as to how it can be reached. This will be replaced by the link resulting from implementation of https://github.com/cf-convention/cf-convention.github.io/issues/469. Based on how other links to are presented on the same web page is is possible to preliminary infer how the link will look like, which is what is used in the draft PR.

**Comment by JonathanGregory** [comment]
Dear @larsbarring 

I agree that putting the location of the `xsd` file into the `xml` could be treated as correcting a defect. However, this PR isn't correcting a defect in Appendix B, really; it's updating it to reflect the correction of a defect in the `xml` file. Since it updates the example in other ways too, I think it should be treated as an enhancement, which I support, rather than a defect. I hope that's OK. Thanks for doing it.

Cheers

Jonathan

**Comment by larsbarring** [comment]
OK to treat it as  an enhancement, in particular as some of the associated issues are enhancements.

**Comment by larsbarring** [comment]
I have now verified that providing a uri (i.e. a web link to an xsd file) works as expected (see https://github.com/cf-convention/cf-convention.github.io/issues/470)) , although of course not with to the specific link suggested here.

**Comment by larsbarring** [comment]
As this a proposal for an `enhancement` it will (if I remember the procedure correctly) need support from two persons (in addition to myself). Hence I would be good to get input from at least one more person (counting @JonathanGregory 's [comment](https://github.com/cf-convention/cf-conventions/issues/516#issuecomment-2016903200) as supportive as now is a an `enhancement`:-).

As this is a small and rather technical change, but a key piece in the string of issues outlined in https://github.com/cf-convention/cf-convention.github.io/issues/457 it would be much appreciated if this issue would not be left hanging.

May I be so bold as to ping @sadielbartholomew, @davidhassell for comments.

Many thanks,
Lars

**Comment by sadielbartholomew** [comment]
I have read the proposal, after prompting by Lars above, and I agree that this is an enhancement, both in terms of categorisation of the Issue and in terms of actively improving the CF Conventions, in particular the infrastructure in this case. I say the latter because being able to easily access the XML schema file is clearly a benefit over it being hard to locate and/or get to, as has correctly been identified is true at present.

So I, for one, support this.

**Comment by larsbarring** [comment]
With this I think that we can start the three-week count down, meaning that the associated PR can be merged on April, 17.

**Comment by larsbarring** [comment]
@sadielbartholomew: May I once again call on you to check the PR #517 and merge if you are satisfied. In particular check lines 17-18 so that I got the terminology right.

Many thanks,
Lars
