### ISSUE TITLE
missing links in wiki page cited in Appendix F

### ISSUE THREAD

**Issue by KCANNIZZARO** [cf-convention/cf-conventions#537]
ON THE PAGE ENTITLED Mapping from CF Grid Mapping Attributes to CRS WKT Elements THERE IS A LINK TO A WEBSITE CALLED REMOTESENSING.ORG, BUT WHEN YOU CLICK ON IT, NO SITE HAS BEEN PUBLISHED TO THAT DOMAIN

**Comment by JonathanGregory** [comment]
@KCANNIZZARO, thanks for your help. Do you mean on the page https://cfconventions.org/wkt-proj-4.html, or some other page? Please could you say where in the page concerned you find this missing link, because I can't find it, and our regular link-checker program hasn't detected it.

**Comment by larsbarring** [comment]
In Table F.1 (in Appendix F) of the Conventions document there are several links to [this wiki page](https://github.com/cf-convention/cf-conventions/wiki/Mapping-from-CF-Grid-Mapping-Attributes-to-CRS-WKT-Elements)., which was last edited in early 2017 and contains links to remotesensing.org (there are other stale links in this page).

**Comment by JonathanGregory** [comment]
Thanks, @larsbarring. I think https://cfconventions.org/wkt-proj-4.html, which is linked to the CF website, is an updated version of https://github.com/cf-convention/cf-conventions/wiki/Mapping-from-CF-Grid-Mapping-Attributes-to-CRS-WKT-Elements. The former doesn't have missing links, I believe, since the web link-checker would find them if it did. If that's right, we should update Appendix F.

**Comment by larsbarring** [comment]
Yes, I agree that Appendix F needs to be updated. We also have https://github.com/cf-convention/cf-conventions/issues/479 that preferably should be dealt with at the same time. And there are a couple of other improvements that are overdue. I have for a long time meant to do something about this, but it has not yet happened.

**Comment by JonathanGregory** [comment]
I have created https://github.com/cf-convention/cf-conventions/pull/563 to remedy this defect, by replacing the references to the wiki page with references to the updated [Mapping from CF Grid Mapping Attributes to CRS WKT Elements](https://cfconventions.org/wkt-proj-4.html), which doesn't contain the broken links.

Since this is a defect issue, the change will be accepted if no-one raises concerns within three weeks (27th Nov).

**Comment by larsbarring** [comment]
I added a couple of comments in the PR regarding files missing in the referred wiki page.

**Comment by JonathanGregory** [comment]
Thanks, @larsbarring. The file `ellipsoid.csv` and the other two `csv` files are attachments to the GitHub wiki page. They were intended to be linked at the bottom of the [CF-WKT](https://cfconventions.org/wkt-proj-4.html) page, which itself is linked from Appendix F, but they appear there as now-defunct URLs to the old trac wiki instead. Whoops.

I have therefore prepared a [website PR](https://github.com/cf-convention/cf-convention.github.io/pull/554) to correct the links in [my modified version](https://jonathangregory.github.io/cf-convention.github.io/wkt-proj-4.html) of the CF-WKT webpage, so that they point to the versions in the GitHub wiki. These links now appear after Table 2 in the webpage, which is where they're relevant. Noticing that the webpage was quite out-of-date, I've brought Tables 1 and 2 up to date and made them compatible with GitHub markdown so their contents are displayed properly.

I have modified the conventions PR #563 to say more precisely where the information can be found e.g. for the `reference_ellipsoid_name`, "Valid names are given in **`ellipsoid.csv`**, following Table 2 in [CF-WKT](https://jonathangregory.github.io/cf-convention.github.io/wkt-proj-4.html)."

I hope this is all OK.

**Comment by larsbarring** [comment]
Thanks Jonathan @JonathanGregory ! 

This looks all good!

**Comment by JonathanGregory** [comment]
No concerns were expressed within three weeks, so I will merge this PR. @KCANNIZZARO, we would like to add you to the [list of contributors](https://cfconventions.org/conventions_contributors.html) - please could you tell us your name and affiliation?
