### ISSUE TITLE
Revert #478, remove inconsistent wording about special characters

### ISSUE THREAD

**Issue by Dave-Allured** [cf-convention/cf-conventions#548]
# Moderator
TBD

# Associated pull request
#549

# Detailed Proposal

Revert PR #478.  Remove this single line from [section 2.3, Naming Conventions](http://cfconventions.org/cf-conventions/cf-conventions.html#_naming_conventions):
"ASCII period (.) and ASCII hyphen (-) are also allowed in attribute names only."

This line was based on my misunderstanding of an earlier version of 2.3 paragraph 1.  That paragraph was later clarified by PR #526, which now says that character restrictions are a recommendation, not a requirement.  Therefore this new sentence is redundant and confusing.

**Comment by JonathanGregory** [comment]
Dear @Dave-Allured 

Thanks for raising this issue. It is relevant to #528 and [discussion 323](https://github.com/orgs/cf-convention/discussions/323), so I've flagged it in both. Since the proposal to add this sentence was accepted as an `enhancement`, with the required amount of support being expressed, I don't think we can reverse that decision as a `defect` i.e. if no-one objects. I think we need support for your proposal to remove the sentence as a new `enhancement`, so I'll change the label.

Best wishes

Jonathan

**Comment by Dave-Allured** [comment]
@JonathanGregory, thanks for switching the label.  That is fine with me.

**Comment by larsbarring** [comment]
I supported inclusion of the text now suggested to be removed. The anticipated main use case that was to create a mechanism form adding localization language tags to attribute names. But as the conversation over in that issue has moved forward in a different issue [see here](https://github.com/cf-convention/cf-conventions/issues/528#issuecomment-2405706703) and subsequent comments. 

Hence I support this proposal to remove the sentence rather than trying to improve it. This has the advantage variable names and and attribute names will use the same character set.

**Comment by JonathanGregory** [comment]
I too support this proposal, for the same reasons as Lars. This issue has sufficient support to be accepted in three weeks, on 30th November, if no-one raises concerns by then.

**Comment by JonathanGregory** [comment]
This change is now accepted. Thanks, @Dave-Allured.
